### ISSUE TITLE
Enforcing Php coding style

### ISSUE THREAD

**Issue by fatimarafiqui** [systers/FirstAide-web#100]
We are following coding standards for all other languages for HTML/CSS. But no coding conventions and style is used for PHP. We can start with PSR-2 coding standard, which is accepted industry wide. It is based on RFC2119.

Link to the guideline:
http://www.php-fig.org/psr/psr-2/

**Comment by AkankshaBodhankar** [comment]
Most of them are covered,. However, this will be useful when a lot of coding will be done during the next development phase that is GSOC. This will be discussed during GSOC 17.

**Comment by aparnavmenon** [comment]
**Description**:
  Readability of code has to be enhanced by enforcing PHP coding standards.

**Mocks**:
PSR-2 coding standard, which is an industry wide accepted coding standard can be used.
Link: http://www.php-fig.org/psr/psr-2/

**Content**:
NA

**Acceptance criteria**: 

- It is verified that the code conforms to the proposed industry standard.

-

**Comment by fatimarafiqui** [comment]
This has been covered in GSoC Phase I @MehaKaushik @npari @prathmeshranaut

**Comment by MehaKaushik** [comment]
Thanks @fatimarafiqui :+1:
