### ISSUE TITLE
Fixing 'Conventions and rules' link in README file

### ISSUE THREAD

**Issue by fatimarafiqui** [systers/FirstAide-web#102]
The link for 'Conventions and rules' has been moved from [https://google.github.io/styleguide/htmlcssguide.xml](https://google.github.io/styleguide/htmlcssguide.xml )
to 
[https://google.github.io/styleguide/htmlcssguide.html](https://google.github.io/styleguide/htmlcssguide.html)

This can be fixed.

**Comment by AkankshaBodhankar** [comment]
Okay
