### ISSUE TITLE
Font size of input text on login page too small

### ISSUE THREAD

**Issue by fatimarafiqui** [systers/FirstAide-web#103]
The font size for the text that we input is really small as compared to other text on the page, making it barely visible. Hence, this can create a change of making errors. This can be fixed by increasing the size by few points.

<img width="1248" alt="fontsize" src="https://cloud.githubusercontent.com/assets/13470643/23585102/76378804-019a-11e7-9910-aae07fa1ec0f.png">

**Comment by AkankshaBodhankar** [comment]
@fatimarafiqui This was suggested in #92 We will keep this as a suggestion and forward it to peace corps and get the new font sizes.
