### ISSUE TITLE
Move form tag from <head> to <body>

### ISSUE THREAD

**Issue by fatimarafiqui** [systers/FirstAide-web#106]
In login.php and registration.php the form tag lies inside the head tag, while it should be inside the body tag.
According to html/css guidelines and standards only the following elements can only go inside the <head> element :
   - title
   - style
   - base
   - link
   - meta
   - script
   - noscript

When the parser sees the form tag, it automatically closes the head element, creates the body element and puts the form element and all subsequent elements inside that body element. Thus, we should move the form tags inside body tag.

Reference links :
[Is there a good reason that a form tag should not exist in the head tag?](http://stackoverflow.com/questions/13850317/is-there-a-good-reason-that-a-form-tag-should-not-exist-in-the-head-tag)
[https://www.w3schools.com/tags/tag_head.asp](https://www.w3schools.com/tags/tag_head.asp)

**Comment by fatimarafiqui** [comment]
@AkankshaBodhankar shall I begin with this?

**Comment by AkankshaBodhankar** [comment]
I'll look into it solve the other issues you have opened

**Comment by fatimarafiqui** [comment]
@AkankshaBodhankar Any updates on this?
