### ISSUE TITLE
Show Password strength checker when the cursor is placed on password input

### ISSUE THREAD

**Issue by shreyans29** [systers/FirstAide-web#109]
Password strength checker  appears before we even start typing.

**Comment by fatimarafiqui** [comment]
@shreyans29 It is already there.

**Comment by shreyans29** [comment]
yes @fatimarafiqui  what I wanted to say was it should come when we type at least one letter. It comes as soon as we click on it.

**Comment by shreyans29** [comment]
![screenshot 978](https://cloud.githubusercontent.com/assets/8592568/23586200/58d76966-01b6-11e7-80c6-c30c23af071d.png)

**Comment by shreyans29** [comment]
This appears even before the user places the cursor on password input.
