### ISSUE TITLE
Highlighting the option selected in the navigational sidebar

### ISSUE THREAD

**Issue by Raxerz** [systers/FirstAide-web#110]
Right now, selecting an option in the navigational side bar opens a new page and the selected option is not being highlighted.
It will be better for the user to know which option he has selected  or which page he is on.
![screenshot from 2017-03-05 14 32 16](https://cloud.githubusercontent.com/assets/16686007/23585931/8e7046c0-01b0-11e7-86eb-3a5f6542b2ec.png)

The above page is the "Personal Security Strategies" page under "Safety tools" section of the nav bar
![screenshot from 2017-03-05 14 34 02](https://cloud.githubusercontent.com/assets/16686007/23585946/e3cc4c2c-01b0-11e7-93a3-6c8021110ef0.png)

The user can be more aware of the page he is on if it is highlighted as shown above.

**Comment by AkankshaBodhankar** [comment]
I think this will do by the title which we provided. The UI has been strictly done with accordance to the requirements
