### ISSUE TITLE
Minor bug in registration form page

### ISSUE THREAD

**Issue by Raxerz** [systers/FirstAide-web#111]
The placeholder for email is incorrectly spelled as "xyz@gmail.xom" and needs to be changed to xyz@gmail.com.

Also, I suggest that it is changed to something more generic like "Enter your email address" for the placeholder text. The other fields' placeholder can be changed as well as the current placeholder is a little misleading and to a naive user it gives a sense of data or text being entered already.
![screenshot from 2017-03-05 14 42 13](https://cloud.githubusercontent.com/assets/16686007/23586031/fd9c8caa-01b2-11e7-8c9d-345d59df084e.png)

**Comment by fatimarafiqui** [comment]
@Raxerz I agree. Placeholders are a little misleading.

**Comment by AkankshaBodhankar** [comment]
Fix this.
