### ISSUE TITLE
More readable error message when twillio unregistered.

### ISSUE THREAD

**Issue by shreyans29** [systers/FirstAide-web#113]
When I click on Help me in circle of trust and click on any of the three Come get me, I need to talk or Call I need an Interruption, It gives an unreadable error message. Should I replace it with a simpler message like twillio not registered. 
![capture](https://cloud.githubusercontent.com/assets/8592568/23586210/833824d4-01b6-11e7-8c53-95174005ae45.PNG)

**Comment by AkankshaBodhankar** [comment]
Resolved in #148
