### ISSUE TITLE
Url twilioSMS twilioCall and groupsms php files appearing directly through URL.

### ISSUE THREAD

**Issue by shreyans29** [systers/FirstAide-web#115]
What i observed in the code is that, it will load the from backend we get a blank number and error if trying to go to this url directly.
![screenshot 979](https://cloud.githubusercontent.com/assets/8592568/23586270/e34e3b8c-01b7-11e7-969c-e03217000d42.png)

**Comment by Dhara159** [comment]
Have you set To number as suggested in readme file

**Comment by shreyans29** [comment]
@Dhara159  No that is not the issue. The issue is we are not supposed to be directly visiting the pages mentioned. It should only be accessible by clicking the button.

**Comment by Dhara159** [comment]
Oh, yes. you are right. i got it.

**Comment by AkankshaBodhankar** [comment]
Looks valid. You can proceed. are you planning to use sessions?

**Comment by shreyans29** [comment]
No, I was actually planning to check for post variables. It solved it that way, it works fine.
