### ISSUE TITLE
Unreadable error message on Circle of trust when Internet connectivity loss.

### ISSUE THREAD

**Issue by shreyans29** [systers/FirstAide-web#116]
When the internet connection is lost and circle of trust, call options are clicked. The error messages are quite unreadable. Can I replace it with "Check your connection and try again."

**Comment by AkankshaBodhankar** [comment]
Sure. Can you post a screenshot ?

**Comment by AkankshaBodhankar** [comment]
@shreyans29 Complete the issues which you have created until now and then you can create new ones. It's becoming unmanageable.

**Comment by shreyans29** [comment]
sure I will stick to the issues I posted. Here is the screenshot 
![capture](https://cloud.githubusercontent.com/assets/8592568/23587795/621d30a0-01d9-11e7-8a02-8f033be351d7.PNG)

**Comment by shreyans29** [comment]
Solved with issue #113, PR #148
