### ISSUE TITLE
Refactor circleOfTrustMessage.js

### ISSUE THREAD

**Issue by fatimarafiqui** [systers/FirstAide-web#117]
In circleOfTrustMessage.js the same code is written multiple times. We can instead parameterise it and avoid the redundancy. 
This would minify the code to enhance the page load speed and improvise it for the better, specially for countries like Uganda, where we have slower internet connectivity.

<img width="953" alt="refactor" src="https://cloud.githubusercontent.com/assets/13470643/23586307/67cb357c-01b8-11e7-8bf7-a94cdf332e12.png">

**Comment by AkankshaBodhankar** [comment]
We have tried removing the redundancy but, it worked the best this way because this file is called multiple times. What solution do you think will reduce this redundancy? mention it in detail.

**Comment by AkankshaBodhankar** [comment]
@fatimarafiqui Please complete the issues which you have opened first. It is becoming unmanagable. Create the next one only once you complete the current ones.

**Comment by fatimarafiqui** [comment]
Instead of using id, we can use classes. The difference between them is an id is unique while a class can be reused multiple times on a page. If you allow me to proceed with this, I can fix it and the number of lines will reduce to one third making it modular. 

And, sure. I thought I can solve issues simultaneously. I found these issues while solving the issues you assigned to me. I will surely keep that in mind.
