### ISSUE TITLE
Set maximum length of Username can be entered

### ISSUE THREAD

**Issue by Dhara159** [systers/FirstAide-web#118]
At the time of registration we can insert much long value for username. So there should be some constraint for this problem.
![screenshot 166](https://cloud.githubusercontent.com/assets/12209363/23586394/d6f80c12-01b9-11e7-9e6c-39a83810a5b3.png)

**Comment by Dhara159** [comment]
I have set the maximum length of username 12 as of now. can you suggest me that what should be the length of the username actually @AkankshaBodhankar

**Comment by fatimarafiqui** [comment]
@Dhara159 Isn't 12 less for username. My github username exceeds 13 characters. Maybe you can increase it to something between 20-25. @AkankshaBodhankar what do you suggest?

**Comment by Dhara159** [comment]
Yes. But I've just put that value only for checking purpose. I'll change the value  as per @AkankshaBodgankar say.

**Comment by AkankshaBodhankar** [comment]
@Dhara159 Use 25

**Comment by Dhara159** [comment]
I have also set the validation rule which is >4 and <26 in js validation.
