### ISSUE TITLE
Store Twilio credentials in a separate file

### ISSUE THREAD

**Issue by fatimarafiqui** [systers/FirstAide-web#119]
Currently twillio credentials are stored in three different files: twilioSMS.php, twilioCall.php and groupsms.php.
We should store the credentials in a separate file due to following reasons:

1. It is cumbersome to copy paste and maintain the credentials at three different locations.
2. Someone can by mistake commit his/her credentials in the PR, thus we can maintain the file in gitignore file to make the system more secure and intact.
3. In future, if the credentials or the token needs to be changed it can be changed at a single location and it would reflect instantly.
4. Overall it would increase security, flexibility to change and reduce chances of human error.

**Comment by AkankshaBodhankar** [comment]
Where do you plan to store them?

**Comment by fatimarafiqui** [comment]
I am planning to store them in a separate file in services, or can create a separate directory named 'includes' and then the path of that file can be added to gitignore.

**Comment by fatimarafiqui** [comment]
#156 This is what I meant, I have stored the google reCaptcha credentials in a separate file (includes/setting.php)

**Comment by AkankshaBodhankar** [comment]
Okay resolve this.
