### ISSUE TITLE
Make better UI for Circle of Trust Page

### ISSUE THREAD

**Issue by Dhara159** [systers/FirstAide-web#120]
On the circleOfTrust.php page, there is an icon of pencil by clicking on which we can go to page where we can edit the contact no. list. And there is a button of Help me and 6 icon of people which are unnecessary.

Suggested design of new page:
1.) Remove Pencil icon and directly show the UI like editComrades.php
2.) Set left orientation for SAVE button and on the right side we can have HELP Me button as same as SAVE button and remove 6 icon of ic_comrade.png. 

If it is okay then i can upload the UI of suggested changes also.

**Comment by fatimarafiqui** [comment]
@Dhara159 I suggested a similar UI enhancement issue. But, as @AkankshaBodhankar told me, this is how peace corps wanted it to be. Moreover, the UI is also in sync with the android application.

**Comment by Dhara159** [comment]
okay. Thanx.

**Comment by AkankshaBodhankar** [comment]
@Dhara159  what @fatimarafiqui is saying is right. If we get any further requirements for improvement from the peace corps we will incorporate them.
