### ISSUE TITLE
Give correct path for dragscroll.js on personalSecurityStrategies.php page

### ISSUE THREAD

**Issue by Dhara159** [systers/FirstAide-web#121]
![screenshot 169](https://cloud.githubusercontent.com/assets/12209363/23586675/de467430-01bf-11e7-8224-fa6df95b96b5.png)

**Comment by AkankshaBodhankar** [comment]
@Dhara159 We have not yet incorporated dragscroll in this module. The requirement for this page can be different and we will work on it once we know how this page should be implemented.
