### ISSUE TITLE
Warning : Issue on login

### ISSUE THREAD

**Issue by fatimarafiqui** [systers/FirstAide-web#122]
I come across this warning while logging in. Is someone else getting the same error?

<img width="1272" alt="warning" src="https://cloud.githubusercontent.com/assets/13470643/23586702/940a933c-01c0-11e7-833e-386100f74ccb.png">

**Comment by Dhara159** [comment]
nope. Not untill now.

**Comment by fatimarafiqui** [comment]
Procedure has some issue so I had to reinstall the db setup. Fixed.
