### ISSUE TITLE
Favicon can be added

### ISSUE THREAD

**Issue by fatimarafiqui** [systers/FirstAide-web#124]
A favicon can be added as it can be easily recognised. It displays our brand as a sign of trust. Differentiate our website, It looks polished and professional (this builds trust and credibility).

<img width="1280" alt="screen shot 2017-03-05 at 16 49 49" src="https://cloud.githubusercontent.com/assets/13470643/23586836/ffe2575e-01c3-11e7-838b-ca5eaac8500d.png">

Examples:
<img width="220" alt="screen shot 2017-03-05 at 16 53 10" src="https://cloud.githubusercontent.com/assets/13470643/23586873/9ca72baa-01c4-11e7-8794-f09649a25541.png">

<img width="246" alt="screen shot 2017-03-05 at 16 53 22" src="https://cloud.githubusercontent.com/assets/13470643/23586874/9d268bca-01c4-11e7-992e-8dfad5c4ba1c.png">

Reference Link: [https://www.hallaminternet.com/why-have-a-favicon/](https://www.hallaminternet.com/why-have-a-favicon/)

**Comment by AkankshaBodhankar** [comment]
Sure. I'll keep this as a suggestion and once we get the icon which the peace corps wish to use we can reopen the issue.

**Comment by fatimarafiqui** [comment]
@AkankshaBodhankar The icon used in the left menu panel, is generally used as favicon. Also I would request you to keep the issues open and put a 'on-hold' tag on it, so that it becomes easier for me to get back to a open issue. Closed issues lose existence. Once you feel that issue will no longer serve the purpose you can close it.

**Comment by AkankshaBodhankar** [comment]
We lose track of the issues currently being worked on and the suggestions are forwarded to peace corps which takes a long time. We always reopen the issue once it is required.
