### ISSUE TITLE
Add icons (call and message) to all the dialogs

### ISSUE THREAD

**Issue by AkankshaBodhankar** [systers/FirstAide-web#13]
Add these two icons as in mockup. Currently, only text is displayed (Voice call and Send message) not the icons

![get help now 2](https://cloud.githubusercontent.com/assets/14356938/18415659/c608808e-7817-11e6-87b4-8aa81f36b778.png)

**Comment by pandilladivya** [comment]
@AkankshaBodhankar, I would like to work on this issue. 

Please allow me to do so.

Thank You! :)

**Comment by AkankshaBodhankar** [comment]
@pandilladivya Sure you can fix this. Make sure you add icons in all the dialogs. There are dislogs in different modules

**Comment by pandilladivya** [comment]
@AkankshaBodhankar 

Kindly review #17

Thanks!

**Comment by pandilladivya** [comment]
kindly review #19 

Thank You :)

**Comment by sudhachauhan** [comment]
@AkankshaBodhankar  is this issue still available to solve?

**Comment by AkankshaBodhankar** [comment]
@sudhachauhan It's been solved and is currently waiting for review

**Comment by AkankshaBodhankar** [comment]
Resolved in #18
