### ISSUE TITLE
Changing cursor to pointer on hovering over "Sign in to Account" button on login page

### ISSUE THREAD

**Issue by Raxerz** [systers/FirstAide-web#130]
![screenshot from 2017-03-06 20 26 56](https://cloud.githubusercontent.com/assets/16686007/23615077/4696f064-02ab-11e7-981e-8ce94f734d58.png)

The cursor does not change to a pointer on hovering over the "Sign in to Account" button.

**Comment by AkankshaBodhankar** [comment]
Yes you can do this.
