### ISSUE TITLE
Warning: mysqli_fetch_row() expects parameter 1 to be mysqli_result, boolean given 

### ISSUE THREAD

**Issue by sudhachauhan** [systers/FirstAide-web#132]
![screenshot 117](https://cloud.githubusercontent.com/assets/17814636/23616103/9c71018e-02ae-11e7-8054-d3fe697a77ae.png)

Anyone getting this error?

**Comment by AkankshaBodhankar** [comment]
@sudhachauhan This will resolve with #107
