### ISSUE TITLE
TYPO 

### ISSUE THREAD

**Issue by sudhachauhan** [systers/FirstAide-web#133]
![screenshot 119](https://cloud.githubusercontent.com/assets/17814636/23617817/4f70ff46-02b4-11e7-9cc4-b50220cc788a.png)
![screenshot 118](https://cloud.githubusercontent.com/assets/17814636/23617818/4f734846-02b4-11e7-9eac-c318f1a2cdec.png)

Can I send a PR?

**Comment by AkankshaBodhankar** [comment]
Just change the strategies I'll let you know about the second one later.
