### ISSUE TITLE
"Drag to move" pages

### ISSUE THREAD

**Issue by sudhachauhan** [systers/FirstAide-web#134]
Among all the pages having this feature only radar.php is showing pop up for this feature.
Is this due to some particular reason or do we need to include it on all the relevant pages?
If not,
Suggestion: pop up on many pages can be irritating sometimes, so can we show some text on these pages?
What is your suggestion? @AkankshaBodhankar 
![screenshot 120](https://cloud.githubusercontent.com/assets/17814636/23618169/78c31d6a-02b5-11e7-8db3-bed6de3b6b19.png)

**Comment by AkankshaBodhankar** [comment]
@sudhachauhan We have kept this to make the UI understandable and we are still planning on many UI aspects including this
