### ISSUE TITLE
Changing database documentation

### ISSUE THREAD

**Issue by shreyans29** [systers/FirstAide-web#141]
With issue #107 and issue #140  we would have to bring some changes in readme file, so that every one can understand the procedure for setting up database.

**Comment by shreyans29** [comment]
@AkankshaBodhankar  Sorry for creating issues without solving the previous ones but I felt they would be very important to avoid redundant work.

**Comment by AkankshaBodhankar** [comment]
@shreyans29 Please resolve other issues, there are many issues which you have opened and unresolved.

**Comment by shreyans29** [comment]
@AkankshaBodhankar  Sorry for creating issues without solving the previous ones but I felt they would be very important to avoid redundant work.  Will solve it ASAP.
