### ISSUE TITLE
Duplicate usernames are being accepted on registration

### ISSUE THREAD

**Issue by Raxerz** [systers/FirstAide-web#149]
Usernames are supposed to be unique but duplicate usernames are being accepted.

**Comment by AkankshaBodhankar** [comment]
@Raxerz We have a unique email for identifying the user, if we use the username to login as well then we can do this and right now the length for username is also fixed to 25 which may not give many options. I will keep this as a suggestion. This is a duplicate issue go through the previous issues which have been created before creating a new one. See #94
