### ISSUE TITLE
Documentation for setting up reCaptcha credentials

### ISSUE THREAD

**Issue by fatimarafiqui** [systers/FirstAide-web#157]
In settings.php, the user needs to enter his/her google reCaptcha credentials to make it work on the localhost. Documentation needs to be updated to explain the same.

**Comment by AkankshaBodhankar** [comment]
Can you elaborate?

**Comment by AkankshaBodhankar** [comment]
This will be done after #62 is closed

**Comment by fatimarafiqui** [comment]
@AkankshaBodhankar This must be fixed ASAP as #156 has been merged. Can I send a PR?

**Comment by AkankshaBodhankar** [comment]
Okay

**Comment by AkankshaBodhankar** [comment]
@fatimarafiqui Are you working on this?

**Comment by fatimarafiqui** [comment]
@AkankshaBodhankar Yes, submitting a PR in few hours.
