### ISSUE TITLE
User has to refill all the details if error occurs on registration page

### ISSUE THREAD

**Issue by Dhara159** [systers/FirstAide-web#163]
@AkankshaBodhankar When user tries to register the form and during registration if any error occurs, user has to refill all the form detail again. So, can we do such thing like user has to fill only that detail where validation was failed. and other detail would be same as filled up.

**Comment by AkankshaBodhankar** [comment]
@Dhara159 Right now, if any errors are occurring then on the registration page the text box of invalid data shows a red mark and the user only fills the required data. In the login page we are using. And this is a duplicate issue go through the previously closed issues before a creating new one. See #94

**Comment by Dhara159** [comment]
No @AkankshaBodhankar. This is my mistake. I have not specified the actual issue. Actually, what I wanted to say is there is no duplicate entry allowed for email-id. So, user don't has to refill all the data when any other error occurs. But if user try to enter duplicate entry for email-id then a pop-up shows with validation message of email-id. And after that user returns to registration page and has to refill data again. So, that is what I was asking to prevent refill of data again after the validation of duplicate email address.

**Comment by Dhara159** [comment]
1.)
![screenshot 182](https://cloud.githubusercontent.com/assets/12209363/23827233/dd86df8e-06d4-11e7-8020-7c47e89647cb.png)
2.)
![screenshot 183](https://cloud.githubusercontent.com/assets/12209363/23827241/e8c34978-06d4-11e7-83ff-f4015fe0a96a.png)
3.)
![screenshot 184](https://cloud.githubusercontent.com/assets/12209363/23827242/ef6c7cb8-06d4-11e7-9eb0-df7e17e10e90.png)
So, what's happening now is
1.) User tries to enter duplicate email-id.
2.) Popup shows with message "User with this email already exists
".
3.)After this message no data are showing on the registration page where user is getting redirect after validation message.
So, can we show all the data except email-id because of which the error was generated.

**Comment by Dhara159** [comment]
Is that okay or should we sort out this?

**Comment by AkankshaBodhankar** [comment]
@Dhara159 You can go ahead with this.

**Comment by Dhara159** [comment]
okay.

**Comment by AkankshaBodhankar** [comment]
@Dhara159 Are you still  interested in working on this?

**Comment by Dhara159** [comment]
yes, @AkankshaBodhankar. I want to work on the problem. As of now, my external university examination is going on. So, is that okay if I will continue working on the project after 24th May?

**Comment by AkankshaBodhankar** [comment]
That will be alright :-)

**Comment by Dhara159** [comment]
I have solved the problem. Here is the working example. 
![data](https://cloud.githubusercontent.com/assets/12209363/26512614/fa97ed2a-4284-11e7-899d-6495eeef8090.gif)

Is it okay?

**Comment by fatimarafiqui** [comment]
@Dhara159 This looks good. Kindly send a PR with the correct changes. Cheers!

**Comment by MehaKaushik** [comment]
Seems good to me, but @fatimarafiqui please do not merge any changes, let two people review it first, then we would go ahead with merging this with master.

**Comment by Dhara159** [comment]
I have updated my branch and now it is up to date with the develop. I have created the PR for this issue. [226](https://github.com/systers/FirstAide-web/pull/226) is the id of PR.

**Comment by AkankshaBodhankar** [comment]
Done

**Comment by fatimarafiqui** [comment]
@npari @MehaKaushik This has already been covered, therefore the issue needs to be closed.
