### ISSUE TITLE
Readme file getting too large, Switch to Distributed documentation

### ISSUE THREAD

**Issue by fatimarafiqui** [systers/FirstAide-web#166]
Due to a large number of enhancements and additions in the project documentation the Readme file has become quite large. We can have a distributed documentation, where we can include contribution guidlines, Database setup etc in different files. @AkankshaBodhankar 

Something like this systers repository: https://github.com/systers/macc

**Comment by AkankshaBodhankar** [comment]
Yes good suggestion. There is one guy who has reported this here #45, which is a subset of this issue. I will get back to you with what files need to be created.

**Comment by fatimarafiqui** [comment]
@AkankshaBodhankar sure.

**Comment by aparnavmenon** [comment]
**Description**

For enhancing readability, the Readme file has to be broken down into chunks, that is, switch to distributed documentation.

**Mocks**

https://github.com/systers/macc

**Content**

NA

**Acceptance criteria**

The Readme file will be evaluated based on the criteria of readability,clarity, understanding and ease of navigation to sections.

**Comment by npari** [comment]
@fatimarafiqui Lets get this done here: https://github.com/systers/FirstAide-web/wiki

**Comment by fatimarafiqui** [comment]
This has been covered in the wiki section.
