### ISSUE TITLE
Open source LICENSE missing.

### ISSUE THREAD

**Issue by fatimarafiqui** [systers/FirstAide-web#168]
It is said often that "Open source simply isn't open source without a proper license. Unless we have explicitly told others that they can modify and reuse our work, We've only showed others our code, We haven't shared it."

We can add MIT license as it is most widely used across all open source projects.

<img width="708" alt="screen shot 2017-03-09 at 13 01 04" src="https://cloud.githubusercontent.com/assets/13470643/23740182/7f1768d2-04c8-11e7-9646-7a71751b5084.png">

Reference links:
[1] https://choosealicense.com/licenses/mit/
[2] https://github.com/blog/1964-open-source-license-usage-on-github-com

**Comment by AkankshaBodhankar** [comment]
@fatimarafiqui I'll have to discuss this issue with others in the community and how other repositories work.

**Comment by fatimarafiqui** [comment]
@AkankshaBodhankar  Sure, I am giving you systers repository links for the ones having it, Just in case you need them.

[1] https://github.com/systers/vms/blob/develop/LICENSE
[2] https://github.com/systers/slack-systers-opensource/blob/master/LICENSE
[3] https://github.com/systers/pchub/blob/develop/LICENSE

**Comment by AkankshaBodhankar** [comment]
Nice. I'll go through them.
