### ISSUE TITLE
Placeholders partially visible

### ISSUE THREAD

**Issue by fatimarafiqui** [systers/FirstAide-web#169]
Placeholders are partially visible on the registration page. This needs to be fixed.

<img width="294" alt="screen shot 2017-03-09 at 22 35 40" src="https://cloud.githubusercontent.com/assets/13470643/23761484/f2e2c086-0518-11e7-8f44-e19d91054b21.png">

**Comment by AkankshaBodhankar** [comment]
What changes will you do to resolve this?

**Comment by fatimarafiqui** [comment]
We can increase the text box size to a few points and align them altogether  to make the placeholders fully visible and also align it to the country list dropdown. @AkankshaBodhankar

**Comment by AkankshaBodhankar** [comment]
@fatimarafiqui This is working fine in my pc. It may be a issue at your end and also because the portal is not responsive. We will do this along with the issue #42 making app responsive.
