### ISSUE TITLE
Username regular expression needs changes.

### ISSUE THREAD

**Issue by shreyans29** [systers/FirstAide-web#171]
Username doesn't accept something like this " abc123def ". The regular expression has to be changed accordingly.

**Comment by AkankshaBodhankar** [comment]
Yes, I've noticed this. You can go ahead.

**Comment by Rupinderwadali** [comment]
@AkankshaBodhankar is @shreyans29 working on this issue? If not can I solve this issue?

**Comment by MehaKaushik** [comment]
@fatimarafiqui may I know the status of this issue ?

**Comment by fatimarafiqui** [comment]
@MehaKaushik This is not a valid issue now. We do not have a username now as discussed in the meeting, only the Users' name would suffice.

**Comment by MehaKaushik** [comment]
Great :D thanks
