### ISSUE TITLE
Alerting users on entering data in the wrong format.

### ISSUE THREAD

**Issue by Raxerz** [systers/FirstAide-web#172]
Right now, only the border of the field changes to red when a user enters data in the wrong format on the registration page.
I suggest in addition to changing the color of the border, alerting the error can help the user to correct it.

**Comment by AkankshaBodhankar** [comment]
We can do this but instead of alerting we can show a text message like in password strength checker.

**Comment by Raxerz** [comment]
Yeah showing a text message would be better. I will go ahead and implement it.

**Comment by AkankshaBodhankar** [comment]
Okay.

**Comment by fatimarafiqui** [comment]
@AkankshaBodhankar @npari @prathmeshranaut @MehaKaushik This is also complete.

**Comment by AkankshaBodhankar** [comment]
Done
