### ISSUE TITLE
Refactor the script to a new file

### ISSUE THREAD

**Issue by shreyans29** [systers/FirstAide-web#175]
Instead of having the script in the html page we can put it in a separate file as in the below screenshot of the file registration.php 

![screenshot 994](https://cloud.githubusercontent.com/assets/8592568/23822434/9b62df02-0672-11e7-9943-eaf12e4cb088.png)

**Comment by AkankshaBodhankar** [comment]
Okay do this.

**Comment by AkankshaBodhankar** [comment]
@shreyans29  Resolve the issues as fast as possible. I understand the problem of duplicate issues but during the next development cycle many issues must not be left unresolved in the repo. Work on the ones which you have created in this week.

**Comment by shreyans29** [comment]
ok @AkankshaBodhankar  I will start solving them.

**Comment by AkankshaBodhankar** [comment]
@shreyans29 Are you still interested in working on this?

**Comment by shreyans29** [comment]
Hi, I am little bit busy with learning technologies for PC prep Kit. I will resolve this as soon as I am done with it but it might take some time.

**Comment by AkankshaBodhankar** [comment]
Alright.

**Comment by AkankshaBodhankar** [comment]
@shreyans29 As you will be working on another project. The issues you have created in this project will be open for contribution.

**Comment by fatimarafiqui** [comment]
@AkankshaBodhankar @prathmeshranaut @MehaKaushik  @npari This is also done as a part of MVT. We can close it.

**Comment by AkankshaBodhankar** [comment]
Done in #231
