### ISSUE TITLE
Add loader during long response time

### ISSUE THREAD

**Issue by Dhara159** [systers/FirstAide-web#177]
This issue is specially for the calling and sms. when user press the button for calling or message, it takes three or four seconds to response Specially on **Circle of trust** page. There is no such loader. On **Get help now** we can see that page is loading by watching on the left side of the tab header. So, can we use such loader to show that his/her response is getting submited?

**Comment by AkankshaBodhankar** [comment]
It's a valid issue. What do you plan to do for this?

**Comment by Dhara159** [comment]
Yes, I have some idea about this and i am trying to sort out by that method but i am also looking for some better solution.
