### ISSUE TITLE
Change collation selection : utf8_general_ci

### ISSUE THREAD

**Issue by fatimarafiqui** [systers/FirstAide-web#179]
Currently while using MySQL with Php we use the default collation i.e latin_swedish_ci . We can change it to utf8_general_ci for better encoding of characters. 
<img width="548" alt="screen shot 2017-03-05 at 17 50 30" src="https://cloud.githubusercontent.com/assets/13470643/23834133/3d8baeb2-0777-11e7-90b3-97ae3c4cd1c6.png">

Reference Link : [What is the best collation to use for MySQL with PHP?](http://stackoverflow.com/questions/367711/what-is-the-best-collation-to-use-for-mysql-with-php)

**Comment by AkankshaBodhankar** [comment]
Yes. I've tried doing this while development the last time but I was facing some issue so I had to revert back to latin. You can give it a shot but make sure everything is working fine.

**Comment by fatimarafiqui** [comment]
@AkankshaBodhankar After doing a lot of research, I found that MySQL collation cannot be altered once the database is created. It can only be changes at the time of database creation. 
Hence I created the database using 'utf8_general_ci' and tested everything. Nothing breaks and it works absolutely fine.

<img width="947" alt="collation" src="https://cloud.githubusercontent.com/assets/13470643/24265049/3c0827e6-1028-11e7-86dc-3ee7df5ea1fc.png">

I would suggest we can add the steps for collation selection in README.md and that will resolve the issue. Shall I send a PR?

**Comment by AkankshaBodhankar** [comment]
@fatimarafiqui Yes

**Comment by prathmeshranaut** [comment]
@fatimarafiqui Please include the code to automatically set the collation at the time of database creation in the `first aide_web.sql` script.

**Comment by fatimarafiqui** [comment]
okay. This will be done in the next pR

**Comment by MehaKaushik** [comment]
May I please know @fatimarafiqui if this is done ?

**Comment by fatimarafiqui** [comment]
@MehaKaushik This is done.

**Comment by MehaKaushik** [comment]
Thanks @fatimarafiqui
