### ISSUE TITLE
Redirect all non working menu options to 'To be added soon' page

### ISSUE THREAD

**Issue by fatimarafiqui** [systers/FirstAide-web#184]
Many options such as PeaceCorpse Policy Summary Sheet, Glossary etc have not been added, but the link is redirected to the page itself, that gives a feeling of a non working link to a new user. We can redirect all such pages temporarily to page named a  comingsoon.php for better user experience, until the features are actually implemented. 

@AkankshaBodhankar  Something like this -
<img width="1280" alt="comingsoon" src="https://cloud.githubusercontent.com/assets/13470643/23908416/f800ccc2-08f9-11e7-957f-6d0a21cb3936.png">

Reference: http://ux.stackexchange.com/questions/26668/what-message-should-we-use-with-under-construction-page

**Comment by AkankshaBodhankar** [comment]
As we are going to implement the new pages soon this won't be necessary.
When the new pages will be added it will be convinent for the developer to
start coding and creating files according to the format and specifications
which will be used then. This would be a valid issue if we had thought
about it before few months back but now as the net development cycle is
very close this won't be necessary.

**Comment by fatimarafiqui** [comment]
@AkankshaBodhankar Okay. I agree with you.
