### ISSUE TITLE
Incorrect alert on twilioSMS.php when Twilio not setup

### ISSUE THREAD

**Issue by fatimarafiqui** [systers/FirstAide-web#185]
When twilio is not setup, the alert must show 'Service Unavailable' as it has been fixed for other page.
But it shows this alert - 
<img width="1273" alt="screen shot 2017-03-14 at 21 27 38" src="https://cloud.githubusercontent.com/assets/13470643/23918908/c93225b4-091a-11e7-9c79-006adb3b3933.png">

@AkankshaBodhankar This can be fixed.

**Comment by AkankshaBodhankar** [comment]
This is a different message. This is because 6666 is not a valid number.
It's not an issue it's a feature. We have put different messages according
to what the problem can be in the alert.

**Comment by fatimarafiqui** [comment]
@AkankshaBodhankar In that case I am unable to edit the number while clicking Contact PCMO, Contact SSM etc. The numbers shown are 5555 , 4444 etc. Also I have removed the twilio setup and still I get the same error. 

Dont you think, in the case where twilio is not setup it should say service unavailable and after setup it should say 'Invalid phone number'

Also, please tell me if these phone numbers are invalid why are we using them?

**Comment by AkankshaBodhankar** [comment]
@fatimarafiqui These are the sample numbers which are used until we get the actual helpline numbers.

**Comment by AkankshaBodhankar** [comment]
Also, service unavailable will be shown when there is no response from the backend. First the issue from the user end has to be resolved only then the backend comes into picture. We are showing the number message for the same reason. Once that is working okay then if we are not able to respond to the request then we show the service unavailable message.

**Comment by fatimarafiqui** [comment]
@AkankshaBodhankar Okay. I understood. Thanks!
