### ISSUE TITLE
More readable alert on twilioCall.php when twilio not setup.

### ISSUE THREAD

**Issue by fatimarafiqui** [systers/FirstAide-web#186]
This can also be fixed like it has been fixed for circle of trust in #113.

<img width="1256" alt="readable_message" src="https://cloud.githubusercontent.com/assets/13470643/23919080/6ffd2e16-091b-11e7-9f96-07e6208cfcd9.png">

**Comment by AkankshaBodhankar** [comment]
Okay. Follow the same procedure for changing the code as done in #113
