### ISSUE TITLE
Unnecessary output of country list json in console : Remove console.log() 

### ISSUE THREAD

**Issue by fatimarafiqui** [systers/FirstAide-web#187]
Due  to console.log() , the whole json of country list is being shown in console. This should be removed, as it has been left by mistake while testing.

<img width="1260" alt="remove console" src="https://cloud.githubusercontent.com/assets/13470643/23919271/43a8d616-091c-11e7-87b3-bb5f37e6f765.png">

**Comment by AkankshaBodhankar** [comment]
@fatimarafiqui Okay. Next time while  resolving a issue try not to leave such unnoticed errors.

**Comment by AkankshaBodhankar** [comment]
@fatimarafiqui Resolve the issues as fast as possible. I understand the problem of duplicate issues but during the next development cycle many issues must not be unresolved in the repo. Work on the ones which you have created in this week.

**Comment by fatimarafiqui** [comment]
@AkankshaBodhankar I will try to resolve the issues as soon as possible.
