### ISSUE TITLE
Complete the main modules

### ISSUE THREAD

**Issue by AkankshaBodhankar** [systers/FirstAide-web#192]
Remaining modules:

Support Services
Sexual Assault Awareness
Policies and Glossary

**Comment by sudhachauhan** [comment]
Can I take up this ?

**Comment by AkankshaBodhankar** [comment]
This will be done during Gsoc 17

**Comment by AkankshaBodhankar** [comment]
Description:
There are three modules which have to be completed. 
Support Services
Sexual Assault Awareness
Policies and Glossary

Mocks:
https://github.com/systers/FirstAide-web/blob/develop/project-docs/prj%20images/slide-menu.jpg 

Content:
The modules can be viewed above in the menu. The last menu items are the three modules. currently, these are not functional. Make them functional and add the appropriate content.

Acceptance criteria:
The content should be updated from MACC which will reflect in the FirstAide web app

**Comment by fatimarafiqui** [comment]
This has been covered in GSoC'17 Phase I. @MehaKaushik @prathmeshranaut @npari

**Comment by MehaKaushik** [comment]
Thank you @fatimarafiqui for completing this.
