### ISSUE TITLE
Integrating with MACC

### ISSUE THREAD

**Issue by AkankshaBodhankar** [systers/FirstAide-web#199]
**Description:**
FirstAide web needs to be Integrated with [macc app](https://github.com/systers/macc).
MACC is a web portal which can be used to update the static content of other applications. Firstaide web app has a lot of static content and there might be a need in future to update or edit the content. To do this, a peace corp volunteer can sign in to the MACC portal, select the Firstaide web app and add content using a form. The content will be updated in the app. 
The FirstAide student has to just get the content using rest API (GET, POST etc.)

**Mocks:**
N/A

**Content:**

**Acceptance criteria:**
User should be able to update content in FirstAide web through MACC

**Comment by fatimarafiqui** [comment]
@AkankshaBodhankar Could you please elaborate the integration process. Do we need to provide a link from MACC to FirstAide home page or integrate the whole Web app in MACC?

**Comment by mish24** [comment]
@AkankshaBodhankar Hello! What's this about?? :) And how would this be done?

**Comment by ReginaTL** [comment]
@AkankshaBodhankar I'm assuming that we are using this: https://github.com/systers/macc and we are using their API to connect to the backend, is this correct?

**Comment by AkankshaBodhankar** [comment]
Description:
Integrate with macc app https://github.com/systers/macc 

Mocks:
NA

Content:
The content of the app can be changed dynamically using the MACC portal. Student has to collaborate with MACC team and get the data using rest.

Acceptance criteria:
The content should be updated from MACC which will reflect in the FirstAide web app
