### ISSUE TITLE
Change font to Avenir Next

### ISSUE THREAD

**Issue by AkankshaBodhankar** [systers/FirstAide-web#20]
Change font to Avenir Next, with "regular" as the main weight for content while "bold" used for buttons. (An alternative is Lato if we can't find a free one (https://www.google.com/fonts/specimen/Lato)

**Comment by fatimarafiqui** [comment]
Can I take this issue?

**Comment by AkankshaBodhankar** [comment]
This issue is currently assigned for Google code- in 2016. You can pick
other issues which do not have the gci label. If you are participating in
gci then claim it there

**Comment by rahulbisht12** [comment]
Hi, Can I use this font http://www.cufonfonts.com/en/font/13217/avenir-next-lt-pro

**Comment by AkankshaBodhankar** [comment]
@rahulbisht12 Sure! You can use it

**Comment by goelsnigdha** [comment]
What is the name of the ZIP file which I am required to download for this task?

**Comment by AkankshaBodhankar** [comment]
You have to download this project. You will find a download Zip at the
right top side of the code

**Comment by j-shubh** [comment]
I have downloaded the font locally  how to store it should i put it in css file

**Comment by AkankshaBodhankar** [comment]
Yes ! Use it in the css files. You will find tutorials online on how yo use
fonts.
