### ISSUE TITLE
Issue in markdown formatting, headings not getting rendered properly : Minor Bug

### ISSUE THREAD

**Issue by fatimarafiqui** [systers/FirstAide-web#201]
The headings are not showing up properly in the README.md file due to spacing issue. 
<img width="661" alt="screen shot 2017-03-21 at 19 41 36" src="https://cloud.githubusercontent.com/assets/13470643/24151491/f72f7f94-0e6e-11e7-9a89-dd97e1fcea0a.png">

@AkankshaBodhankar Can I fix it?

**Comment by AkankshaBodhankar** [comment]
When has this problem arised? This was not happening before.

**Comment by fatimarafiqui** [comment]
@AkankshaBodhankar I noticed it just after creating a PR for Recaptcha documentation. Then I rechecked the main develop branch to verify if it was done from my side. But, No. It might have arise from previous changes done to README.md

**Comment by kamsuri** [comment]
![screenshot from 2017-03-22 02-36-13](https://cloud.githubusercontent.com/assets/14004808/24170921/7f4cb8ea-0ea8-11e7-9ea2-800223e6e25f.png)

**Comment by fatimarafiqui** [comment]
@kamsuri It is not showing fine in your screenshot as well. Hash must not be visible and the headings must be bold. 
@AkankshaBodhankar This can be resolved by making ###Documentation -> ### Documentation. Just the spacing is missing.

**Comment by AkankshaBodhankar** [comment]
@fatimarafiqui Do this.

**Comment by kamsuri** [comment]
@fatimarafiqui I thought you were referring to the merging of headings with content, but now i got it.
