### ISSUE TITLE
Session should also be unset in logout.php before destroy

### ISSUE THREAD

**Issue by kamsuri** [systers/FirstAide-web#203]
By doing this session variable will be unset for the run-time

**Comment by Dhara159** [comment]
@kamsuri i think this issue is fixed in #91.

**Comment by kamsuri** [comment]
@Dhara159 I haven't seen any mention of this conflict in your isssue, your issue will be dealing with the keep me logged in feature. You can add this obviously but you haven't directly specified this glitch, it's just a coding technique not a feature. @AkankshaBodhankar should i submit its PR will it be dealt in #91.

**Comment by AkankshaBodhankar** [comment]
@kamsuri Can you elaborate?

**Comment by Dhara159** [comment]
okay. Got that @kamsuri .

**Comment by kamsuri** [comment]
@AkankshaBodhankar In logout.php we are directly destroying the session but before that it should also be unset, as it will unset the session variable for the run time as well. It is just a way of improving our code.
What i am saying is just a one line code which needs to be added.

**Comment by AkankshaBodhankar** [comment]
@kamsuri Yes this issue is valid. Are you working on it?

**Comment by AkankshaBodhankar** [comment]
Due to no response for more than 15 days this will be an open issue.

**Comment by AkankshaBodhankar** [comment]
@fatimarafiqui Is this taken care of during restructuring?

**Comment by fatimarafiqui** [comment]
This will be done after the session management is incorporated. This must be kept open for now.

**Comment by AkankshaBodhankar** [comment]
Okay

**Comment by MehaKaushik** [comment]
@fatimarafiqui This is done right ??

**Comment by fatimarafiqui** [comment]
@MehaKaushik Yes, Its done

**Comment by MehaKaushik** [comment]
Thanks
