### ISSUE TITLE
No check on username 

### ISSUE THREAD

**Issue by kamsuri** [systers/FirstAide-web#204]
Username with only spaces that is a blank username is also acceptable in this code and also username having spaces is also acceptable. As u can see in the screenshot the first one is only spaces and in the second one it is invalid username as username should be of one word only
![image](https://cloud.githubusercontent.com/assets/14004808/24171220/8cd820c0-0ea9-11e7-8cd2-a9d0b2a9ab7a.png)

**Comment by fatimarafiqui** [comment]
@kamsuri @AkankshaBodhankar  This is a duplicate issue and similar to #171

**Comment by kamsuri** [comment]
#171 is accepted but still there is problem with username.

**Comment by AkankshaBodhankar** [comment]
This will be done in #171 and #137
