### ISSUE TITLE
Update the Documentation for Twilio credentials stored in a file

### ISSUE THREAD

**Issue by fatimarafiqui** [systers/FirstAide-web#208]
Documentation needs to be updated corresponding to #119 as soon as #207 gets merged for Twilio credentials that are stored in a single file.

**Comment by fatimarafiqui** [comment]
@AkankshaBodhankar any updates on this? Shall I send a PR?

**Comment by AkankshaBodhankar** [comment]
@fatimarafiqui Sure

**Comment by fatimarafiqui** [comment]
Updated in the wiki section
