### ISSUE TITLE
Update the circle of trust with the selected icons

### ISSUE THREAD

**Issue by AkankshaBodhankar** [systers/FirstAide-web#209]
**Description:**
The icons will be selected and posted here soon. The circle of trust icons has to be updated with the new icons.

**Mocks:**
https://github.com/systers/FirstAide-web/blob/develop/project-docs/prj%20images/Screenshot%20(621).png 
_Note: Final icons will be posted here_

**Content:**
NA

**Acceptance criteria:**
- The circle of trust should reflect the new approved icons
- Screenshots should be submitted in PR of the circle of trust page with the new icons

**Comment by safrin96** [comment]
Hi, Can i work on it and use it for the GSoC proposal?

**Comment by AkankshaBodhankar** [comment]
@safrin96 You can include this in your proposal. All the GSOC 17 labeled issues will be resolved during the GSOC period.

**Comment by safrin96** [comment]
Hi, when i am trying to register an account it is giving this error. 
Trying to get property of non-object in C:\xampp\htdocs\registration.php on line 111

**Comment by fatimarafiqui** [comment]
@npari @MehaKaushik This is covered and it should be closed.
