### ISSUE TITLE
Validation and strength checker for password 

### ISSUE THREAD

**Issue by AkankshaBodhankar** [systers/FirstAide-web#21]
During registration add a password strength checker and add validation.
For example,
The password should have minimum 8 characters. Display appropriate message to the right of the textbox alerting the user
A password strength checker something like this:

![ajax-password-strength-meter-script](https://cloud.githubusercontent.com/assets/14356938/20389820/9621842e-acf1-11e6-8d1b-f72ae84d30b5.gif)

**Comment by rahulbisht12** [comment]
Is anyone working on this issue ?

**Comment by AkankshaBodhankar** [comment]
No your cab claim.it on gci

**Comment by AkankshaBodhankar** [comment]
Solved #44
