### ISSUE TITLE
Add a back button for the Get Help Now2 content pages

### ISSUE THREAD

**Issue by mani-rao** [systers/FirstAide-web#210]
The content on Get Help Now 2(PCSaves, Office of victim advocacy, Office of Inspector General and Office of Civil Rights and Diversity)  when clicked open to a description page where there could be a back button to navigate back to Get Help Now2 page. (As opposed to having to click on the sidebar menu)

**Comment by AkankshaBodhankar** [comment]
@mani-rao I think this might create redundancy as the user can navigate to the get help now main section using the menu. If we add a back button for it then, we will have to add it for other similar modules as well. Also, the UI will be much cleaner this way.
