### ISSUE TITLE
favicon missing on the site

### ISSUE THREAD

**Issue by muskanbararia** [systers/FirstAide-web#214]

**Comment by fatimarafiqui** [comment]
@muskanbararia This is a duplicate issue. Refer #124

**Comment by muskanbararia** [comment]
@AkankshaBodhankar instead of closing this issue, you can simply add the code to link favicon. (refer my pull request #215 ) You can later on add the logo of your choice.

**Comment by AkankshaBodhankar** [comment]
This is a duplicate issue. Please go through the previous issues before creating one. Also, do not sent a PR without getting approval. Read the rules of contributing in the readme file.
