### ISSUE TITLE
Unified css compostion and a single head.php file

### ISSUE THREAD

**Issue by muskanbararia** [systers/FirstAide-web#216]
Instead of writing <head> .... </head> in every file, it can be written once under head.php which can be included in every file. It will make code short and more readable.

Also, instead of having different css corresponding to different files, a uniform css file can be composed.

**Comment by fatimarafiqui** [comment]
@muskanbararia I guess this also a part of #42 where the css and html files need to be minified. @AkankshaBodhankar @aparnavmenon can tell you better I guess.

**Comment by muskanbararia** [comment]
@fatimarafiqui No. It require not only css file modifications but also in the php files.

**Comment by MehaKaushik** [comment]
@muskanbararia, can you explain how this issue would not be covered by #42  ? #42 will involve minifying css and html/php files.

**Comment by AkankshaBodhankar** [comment]
This issue will be covered under #11 and after restructuring of the app this won't be necessary. Also, there has been no response from @muskanbararia for more than 2 months.
