### ISSUE TITLE
Implement Bcrypt Encryption for password.

### ISSUE THREAD

**Issue by fatimarafiqui** [systers/FirstAide-web#218]
While going through various encryption techniques I found that md5 is one of the weakest hashing techniques and is easily hackable. Information regarding sexual assualt, contact details of comrades are very personal and should not be compromised when it comes to security. Thus we should use bcrypt for encryption technique that is more secure and involves hashing and salting as it provides the following benefits:

1. Bcrypt will silently truncate any password longer than 72 characters.
2. Bcrypt will truncate after any NULL characters.

Reference links:
[1] [SHA1 vs md5 vs SHA256: which to use for a PHP login?](http://stackoverflow.com/questions/2235158/sha1-vs-md5-vs-sha256-which-to-use-for-a-php-login)
[2] http://searchsecurity.techtarget.com/news/4500270165/MD5-vulnerability-renews-calls-for-faster-SHA-256-transition

**Comment by yyang08** [comment]
can i work on this?

**Comment by AkankshaBodhankar** [comment]
@fatimarafiqui I'm adding this task to GSOC 17.

**Comment by AkankshaBodhankar** [comment]
@fatimarafiqui For the current app, the data we have is not very sensitive. The md5 we are using to encrypt will suffice for now. so, I'm closing this issue.

**Comment by fatimarafiqui** [comment]
@AkankshaBodhankar Okay.
