### ISSUE TITLE
Data Toggle Validator can be added

### ISSUE THREAD

**Issue by kavithaenair** [systers/FirstAide-web#219]
Issue: Feature Request

Description:
Now we don't have a toggle validator(data error should be shown to the user) when each time the user skips a field and clicks TAB and goes to other field in login and signup form.
This feature can be added as a part of Exception Handling.

**Comment by kavithaenair** [comment]
I want to fix this.

**Comment by MehaKaushik** [comment]
@kavithaenair, sorry for the delay in reply. If you are still interested in fixing this, you can go ahead.

**Comment by MehaKaushik** [comment]
@kavithaenair are you still interested in working on this?

**Comment by kavithaenair** [comment]
@mehakaushik you can take this up. :)

**Comment by AkankshaBodhankar** [comment]
@kavithaenair @MehaKaushik is also one of the mentors for this project. She was asking if you are working on it right now or not.

**Comment by kavithaenair** [comment]
Oh sorry am new to this organisation. Am not working on it.

**Comment by AkankshaBodhankar** [comment]
That's okay :-). This issue will be kept as free.

**Comment by AkankshaBodhankar** [comment]
Done in #231
