### ISSUE TITLE
Add comments to the css files

### ISSUE THREAD

**Issue by AkankshaBodhankar** [systers/FirstAide-web#22]
**Pick only one file at a time.** 
This is a beginner task. You can claim one css file and start working on it
Make sure the format you use while adding comments is according to this 
https://perishablepress.com/obsessive-css-code-formatting-organization-comments-and-signatures/

**Comment by AkankshaBodhankar** [comment]
You can claim any css file except sweetalert.css

**Comment by rahulbisht12** [comment]
Hi, I am taking loginAndRegistration.css file to add comments on it.

**Comment by AkankshaBodhankar** [comment]
@rahulbisht12 Sure you can go ahead

**Comment by pgadige** [comment]
I'd want to claim menu-css.css file to add comments

**Comment by AkankshaBodhankar** [comment]
@pgadige Sure. Follow the conventions mentioned in the above link.

**Comment by kamsuri** [comment]
Hi! Can i take gethelpnow-style.css for adding comments in it?

**Comment by AkankshaBodhankar** [comment]
Sure. But, stick to the format

**Comment by kamsuri** [comment]
Alright, i will submit the code for review soon.

**Comment by kamsuri** [comment]
Please review the code

**Comment by shreyans29** [comment]
can I take welcome-style.css

**Comment by AkankshaBodhankar** [comment]
@shreyans29 Sure

**Comment by shreyans29** [comment]
Hi, according to
 https://perishablepress.com/obsessive-css-code-formatting-organization-comments-and-signatures 
it says, the CSS classes are better if grouped using the following protocol.

global settings (resets, scrollbars, etc.)
primary layout structure (body, primary divs)
secondary layout structure (header, footer, sidebar)
tertiary layout structure (page regions, floats)
text-related treatments (headings, paragraphs, lists)
images, links, and other salient features (pre, code)
general styles (forms, tables, buttons, acronyms et al)
general classes (.clear, .center, .right, .left, etc.)
miscellaneous stuff and template code

But I found the classes arranged by alphabetic order. So while commenting, should I change the class order to match it, or just add comments and leave the order undisturbed?

**Comment by AkankshaBodhankar** [comment]
@shreyans29 All the css files have been arranged alphabetically according to google css format. Try to stick to it.

**Comment by shreyans29** [comment]
Okay.

**Comment by fatimarafiqui** [comment]
Can I take loginandRegistration.css?

**Comment by safrin96** [comment]
Hi, Can i take safety-tools.css ? Also i wanted to submit a GSoC proposal for first-aide project. so do i do it with this issue?

**Comment by npari** [comment]
@MehaKaushik Is this a duplicate?

**Comment by MehaKaushik** [comment]
No, the other one is for javascript files.

**Comment by fatimarafiqui** [comment]
This is done.
