### ISSUE TITLE
Need to add validation in Add the Comrade Numbers fields

### ISSUE THREAD

**Issue by Rupinderwadali** [systers/FirstAide-web#221]
Validation on max. numbers as well as symbol "-" and character "e" 
![screenshot from 2017-04-23 00 03 51](https://cloud.githubusercontent.com/assets/12759137/25307121/445ef5fc-27b9-11e7-8217-4ecde886812d.png)

**Comment by AkankshaBodhankar** [comment]
@Rupinderwadali This is a duplicate issue. #23
