### ISSUE TITLE
Text alignment Issue

### ISSUE THREAD

**Issue by Rupinderwadali** [systers/FirstAide-web#222]
I think text start from the starting of the div instead of the center of the div. It makes more symmetry to start the text from the beginning. 
![screenshot from 2017-04-23 00 14 22](https://cloud.githubusercontent.com/assets/12759137/25307187/29d2804a-27ba-11e7-8a92-71514db69f2c.png)
![screenshot from 2017-04-23 00 16 32](https://cloud.githubusercontent.com/assets/12759137/25307188/29d42e7c-27ba-11e7-8695-9602474b37fa.png)

**Comment by AkankshaBodhankar** [comment]
@Rupinderwadali This is a valid issue. Go ahead with it.

**Comment by AkankshaBodhankar** [comment]
@Rupinderwadali Are you working on this?

**Comment by fatimarafiqui** [comment]
@Rupinderwadali Please update us if you are still interested in working on this.

**Comment by AkankshaBodhankar** [comment]
Due to no response by @Rupinderwadali for more than 15 days. This can be done under responsiveness part of GSOC17.

**Comment by AkankshaBodhankar** [comment]
Done in #231
