### ISSUE TITLE
Change icons in circle of trust 

### ISSUE THREAD

**Issue by AkankshaBodhankar** [systers/FirstAide-web#25]
The icons need to be updated in the circle of trust. The images to be used will be selected soon.

**Comment by sudhachauhan** [comment]
hello @AkankshaBodhankar 
can you please guide me how to claim an issue on gci?

**Comment by AkankshaBodhankar** [comment]
@sudhachauhan Before resolving this issue you will have to create new icons. Once the icons are created we can use them in the code. You can claim the issue "Create new icons for circle of trust" on gci

**Comment by sudhachauhan** [comment]
#30

**Comment by sudhachauhan** [comment]
#25

**Comment by dannymout** [comment]
I've created new icons.

<img src="http://i.imgur.com/56f95IX.png">
<img src="http://i.imgur.com/XSC6M3U.png">
<br>
<img height="500" src="http://i.imgur.com/OTkLqpT.png">

Here is an Imgur link to it: http://imgur.com/a/Z4AGW

**Comment by sandarumk** [comment]
Help me button needs to show urgency. hence try to use red there. The font help me should match the app's font. Can you do these two modifications to the icons?

**Comment by sandarumk** [comment]
@dannymout Try to use this red #B71234 which is PC brand identity colour.

**Comment by dannymout** [comment]
OK, I've made the changes. The background colour of the "Help Me" button is `#B71234` and I've set the font to SF UI Display, which is the font used in the app. I'll send the zip on GCI.

**Comment by dannymout** [comment]
I have implemented the new icons in the iOS version of the app. I've made a [PR](https://github.com/systers/FirstAide-iOS/pull/26).

**Comment by sandarumk** [comment]
@dannymout As you can see the GCI tasks are multiple instance tasks. So we are going to compare and select the best icons submitted by the students and then open this task for actual implementation. That is why this task is on hold. You don't need to add the icons just yet. But if your icons selected as the best, we will let you know and merge the PR after reviewing. 
One more thing is this issue is for FirstAide web. For iOS we will create a new issue after the icons were selected. Then you can reference your PR from there. Linking multiple projects is not a good practice when submitting PRs.

**Comment by YashBit** [comment]
Created New Icons for Circle Of Trust Examples of implementation on FirstAide-web and FirstAide-iOS .


![usericon1](https://cloud.githubusercontent.com/assets/20094677/21578161/317cf242-cf9c-11e6-9163-6fe41a7e630c.png)
![button3](https://cloud.githubusercontent.com/assets/20094677/21578162/3280114c-cf9c-11e6-89ed-d652ae0bc6bb.png)
![simulator screen shot 31-dec-2016 8 24 03 pm](https://cloud.githubusercontent.com/assets/2009467
<img width="1280" alt="screen shot 2016-12-31 at 9 04 00 pm" src="https://cloud.githubusercontent.com/assets/20094677/21578175/ae500520-cf9c-11e6-9275-e42f647eef06.png">
7/21578163/35c74e10-cf9c-11e6-9ff1-c1bd70fa9360.png)

**Comment by AkankshaBodhankar** [comment]
Yash have you made the icons for all the resolutions of Android. It should support multiple screens.  Check this link to know more about it https://developer.android.com/guide/practices/screens_support.html

**Comment by jacqueline8711** [comment]
I created these icons for FirstAide:
<img width="96" alt="help_button_192" src="https://cloud.githubusercontent.com/assets/16260112/21738721/269bd3e0-d48b-11e6-9323-4fd0e97b0096.png">
<img width="96" alt="edit_button_192" src="https://cloud.githubusercontent.com/assets/16260112/21738722/29de02b2-d48b-11e6-8155-3e8a4ba25470.png">
<img width="96" alt="person_icon_192" src="https://cloud.githubusercontent.com/assets/16260112/21738719/0fd65310-d48b-11e6-929a-01cacfc6a8af.png">


![screenshot_20170107-031537](https://cloud.githubusercontent.com/assets/16260112/21738714/fc177afc-d48a-11e6-8be1-b0949135f0bf.png)

I attached other resolutions (36x36, 48x48, 72x72, 96x96, 144x144, 192x192, original ~ 1000x1000) in the GCI task

**Comment by AkankshaBodhankar** [comment]
Have you made icons which are compatible for multiple screens in Android ?
See my above comment for the link.
