### ISSUE TITLE
Add country code dropbox in the edit page of circle of trust

### ISSUE THREAD

**Issue by AkankshaBodhankar** [systers/FirstAide-web#26]

**Comment by sudhachauhan** [comment]
@AkankshaBodhankar  please allow me to solve this issue.

**Comment by sudhachauhan** [comment]
if no one is assigned this issue, may I work on this?

**Comment by AkankshaBodhankar** [comment]
Sure it should have a drop down with list if countries and then country
code should load in the drop down. I'll let you know the list if countries
okay.

**Comment by AkankshaBodhankar** [comment]
@MeepyMay This issue requires a list of countries where the application is used by peace corps so we can add countries and country codes accordingly

**Comment by sudhachauhan** [comment]
when can i get the list?

**Comment by AkankshaBodhankar** [comment]
@sudhachauhan I've requested for the list, it may take a little time as we have to contact the peace corps

**Comment by AkankshaBodhankar** [comment]
@sudhachauhan The list of countries can be found in this link : https://www.peacecorps.gov/countries/
Add one dropdown at the top of edit page in circle of trust. Once we select the country, the country code should be loaded in the current edit box.

**Comment by sudhachauhan** [comment]
![screenshot 89](https://cloud.githubusercontent.com/assets/17814636/21751154/49bf8cb4-d5e8-11e6-8326-1335276031eb.png)
![screenshot 90](https://cloud.githubusercontent.com/assets/17814636/21751155/4f6e8fa2-d5e8-11e6-8a1e-279942d4ed23.png)
hey! these are the screenshots.
1.updated the phone number validation with the '+' sign.
2.selecting the country from the top select menu will make respective dial code appear in the current edit input on focus.
if it's all right, should I pull the request?

**Comment by AkankshaBodhankar** [comment]
Can you make the drop down smaller and the text boxes as they were before
one below another. Also, can you post the screenshot of the phone numbers
getting loaded and saved.

**Comment by sudhachauhan** [comment]
![screenshot 95](https://cloud.githubusercontent.com/assets/17814636/21773595/bbc6d196-d6b5-11e6-9a64-53ee8cbcbd6f.png)
![screenshot 91](https://cloud.githubusercontent.com/assets/17814636/21773596/bbe3a578-d6b5-11e6-819c-05cf3a0bdffb.png)

**Comment by AkankshaBodhankar** [comment]
Make the text boxes aligned one below another

**Comment by sudhachauhan** [comment]
![screenshot 96](https://cloud.githubusercontent.com/assets/17814636/21775959/3c6f79b2-d6be-11e6-9bbc-c70f646d92a6.png)

**Comment by AkankshaBodhankar** [comment]
Looks good.

**Comment by AkankshaBodhankar** [comment]
On hold till we get the list of all the countries.

**Comment by AkankshaBodhankar** [comment]
Add the countries listed in #11

**Comment by AkankshaBodhankar** [comment]
The PR in progress for this #66

**Comment by npari** [comment]
@MehaKaushik Is this still relevant?

**Comment by fatimarafiqui** [comment]
@npari No, This issue is no longer relevant as we are saving the country and country codes at signup.
