### ISSUE TITLE
Making application Responsive

### ISSUE THREAD

**Issue by rahulbisht12** [systers/FirstAide-web#42]
It would be great if we can make the application responsive for mobile devices also.

![p4](https://cloud.githubusercontent.com/assets/16523310/20830682/b3f923c8-b8a7-11e6-9a0d-828d4e0cf60d.png)

# Fixes
We can do it in 2 ways

- Add the third party libraries like bootstrap, Material design lite etc. This will require a lot of changes to be done in our part i.e in css and php files. [Easy to manage in large projects]
- Second one is to restyle our own css classes and add the media queries into it.

**Comment by keshashah** [comment]
Would you like to fix it? I can add it in GCI tasks :)

**Comment by AkankshaBodhankar** [comment]
Yes this had to be done! Will get back to you if issue is up for solving immediately

**Comment by rahulbisht12** [comment]
@keshashah @AkankshaBodhankar Yes I am interested in working on this :)

**Comment by AkankshaBodhankar** [comment]
Okay I'll get back you if we create a task

**Comment by keshashah** [comment]
@rahulbisht12 You can claim one instance of https://codein.withgoogle.com/dashboard/tasks/4881890746040320/ Good luck! :)

**Comment by AkankshaBodhankar** [comment]
@rahulbisht12 Are you working on this?

**Comment by kamsuri** [comment]
Hi! Can I work on this?

**Comment by AkankshaBodhankar** [comment]
This is assigned to Rahul.We will wait for few more days until we hear back from him.

**Comment by kamsuri** [comment]
Okay

**Comment by rahulbisht12** [comment]
@AkankshaBodhankar I am now preparing for my 12 board Exams. So I will not be available for some time. You can assign the tasks to the interested peoples. @manishbisht Please look into the issues of this project.

**Comment by AkankshaBodhankar** [comment]
This is an issue which needs a lot of modification. We will keep this for GSOC 17.

**Comment by manishbisht** [comment]
Any more issues for GSoC'17 so that I can make a list of issues and then submit it in my proposal.

**Comment by AkankshaBodhankar** [comment]
Not right now.

**Comment by Rupinderwadali** [comment]
@AkankshaBodhankar I am willing to work on this issue. I have some experience of responsive UI and will update you soon after the task assignment.

**Comment by AkankshaBodhankar** [comment]
Description:
Make the application responsive to fit all types of screen

Mocks:
http://mediaspawn.com/wp-content/uploads/2013/04/Responsive-Websites-on-Devices.jpg 

Content:
Decide which technology will be appropriate, get the approval from mentors and make the app responsive

Acceptance criteria:
Add the feature and make a PR with appropriate screenshots.

**Comment by v786** [comment]
Is this issue up for GSoC 2017 ? I would like to take it up if it is.

**Comment by npari** [comment]
@v786 Thats right, it is open for GSoC17. Every issue with the label **GSoC17** should be considered in your proposal.

**Comment by fatimarafiqui** [comment]
@MehaKaushik @npari @prathmeshranaut This has been covered in GSoC'17 Phase I

**Comment by MehaKaushik** [comment]
Closing this issue, since it is covered by @fatimarafiqui
