### ISSUE TITLE
Create Contributing.md file

### ISSUE THREAD

**Issue by rahulbisht12** [systers/FirstAide-web#45]
CONTRIBUTING.md file can be created in this repo so that we can write all our coding standards there and other the contributers can follow it

**Comment by AkankshaBodhankar** [comment]
Good Suggestion! We generally include the contributing rules and instructions in the readme.md file. We are still working on it, for now we can keep this as a suggestion. As far as implementation is concerned we will keep it on hold.

**Comment by AkankshaBodhankar** [comment]
We will inform the peace corps and org about this along with other suggestions. For now, this will be closed. We will reopen the issue once it gets accepted.
