### ISSUE TITLE
Close Travis CI checks

### ISSUE THREAD

**Issue by AkankshaBodhankar** [systers/FirstAide-web#47]

**Comment by fatimarafiqui** [comment]
Can you elaborate the issue please? I did not get the issue.

**Comment by AkankshaBodhankar** [comment]
This issue has to be handled at our end. You can contribute to the issues
which are labeled as free.

**Comment by fatimarafiqui** [comment]
okay.

**Comment by sudhachauhan** [comment]
My PR is failing this travis CI check.....what should I do? @AkankshaBodhankar

**Comment by AkankshaBodhankar** [comment]
Let it be even if it shows checks failed.

**Comment by AkankshaBodhankar** [comment]
Solved
