### ISSUE TITLE
hashing the passwords

### ISSUE THREAD

**Issue by rahulbisht12** [systers/FirstAide-web#48]
Right now the passwords are saved in database in plain text. It would be better if we hash the password and then save it to database. It will improves the security.

![p23](https://cloud.githubusercontent.com/assets/16523310/20886064/3133afc4-bb1a-11e6-8146-202cc7dbe2fe.png)

**Comment by AkankshaBodhankar** [comment]
Good suggestion!

**Comment by fatimarafiqui** [comment]
Is it available? Can I take it?

**Comment by AkankshaBodhankar** [comment]
Generally the person who creates the issue is assigned to the task automatically. You can ask @rahulbisth12 if he is not solving it then you can take it up

**Comment by fatimarafiqui** [comment]
@rahulbisht12 Please let me know if I can take it.

**Comment by rahulbisht12** [comment]
@fatimarafiqui Yes, I will be working on it after next few days.

**Comment by fatimarafiqui** [comment]
@rahulbisht12   Its been a long time now. Are you still interested in taking it up? @AkankshaBodhankar

**Comment by AkankshaBodhankar** [comment]
@rahulbisht12 Are you working on it? If yes, can you tell how are you planning to solve this issue.

**Comment by VictorAlagwu** [comment]
It is possible @rahulbisht12 is no longer working, onn the project ,if there is no one interested,I would like to work on it,and I would made use of bcrypt hashing algorithum

**Comment by fatimarafiqui** [comment]
I have been willing to take the issue from a very long time now. But, he is not replying. @AkankshaBodhankar Can I take this now please?

**Comment by VictorAlagwu** [comment]
I think @fatimarafiqui should work on the project since @rahulbisht12 is not responding , @AkankshaBodhankar ,I am really to assist if my help is required

**Comment by fatimarafiqui** [comment]
@AkankshaBodhankar I have been waiting for a long time, since December for @rahulbisht12 to respond on this issue, I had also dropped a mail to him for the same and no response. Please give your on call on whether I should create a pull request or not. I have done it on my local machine. Please.

**Comment by fatimarafiqui** [comment]
@AkankshaBodhankar Rahul wont be working on this, he wrote it few days back. I am working on this now. Is it okay?
<img width="892" alt="screen shot 2017-03-05 at 12 44 20" src="https://cloud.githubusercontent.com/assets/13470643/23585319/94282272-01a1-11e7-86e3-f1cb8afc7231.png">

**Comment by AkankshaBodhankar** [comment]
@fatimarafiqui Okay
