### ISSUE TITLE
Unnecessary redirection on index.php

### ISSUE THREAD

**Issue by fatimarafiqui** [systers/FirstAide-web#49]
index.php redirects to login.php after 2 seconds of delay which is an unnecessary redirect. login.php can be integrated with index.php and a loading screen with Peace Corps logo can be integrated.

**Comment by AkankshaBodhankar** [comment]
It's mandatory to have a splash screen for the application and a different login page. I would like to specify that the firstaide web is according to the ios and android. It's in the requirements of the app. However I will put forward your suggestions when the org contacts the peace corps who decide the prototype and requirements. That's the reason why another page has been dedicated for it. You can check the initial prototype posted in the issues.
