### ISSUE TITLE
Gremlins  

### ISSUE THREAD

**Issue by YashBit** [systers/FirstAide-web#52]
FirstAide-web 
Random Characters show up in pages when the preview of the website is seen . This can be avoided by using UTF-8 .
<img width="549" alt="screen shot 2016-12-29 at 1 10 16 pm" src="https://cloud.githubusercontent.com/assets/20094677/21539504/791cf974-cdcd-11e6-87fc-d526d8ff9ee7.png">
<img width="740" alt="screen shot 2016-12-29 at 12 42 05 pm" src="https://cloud.githubusercontent.com/assets/20094677/21539507/7baeef9e-cdcd-11e6-91ef-2984f91e4636.png">

**Comment by YashBit** [comment]
@AkankshaBodhankar  Hi , as this is valid could a task be created for the same ?

**Comment by AkankshaBodhankar** [comment]
@YashBit Are you willing to solve this issue?

**Comment by YashBit** [comment]
@AkankshaBodhankar Yeah , I will try to solve it and make the PR . But I have my exams and I Amby not get free time.  So please don't assign it to me . I will try to make the PR .

**Comment by AkankshaBodhankar** [comment]
@YashBit Okay then, this issue will be free to solve and anyone can claim it. Don't worry about it @YashBit

**Comment by fatimarafiqui** [comment]
Can I take this issue?

**Comment by AkankshaBodhankar** [comment]
Sure

**Comment by AkankshaBodhankar** [comment]
@fatima are you working on this ?

**Comment by fatimarafiqui** [comment]
@AkankshaBodhankar Yes, will open a pull request very shortly.

**Comment by AkankshaBodhankar** [comment]
Solved
