### ISSUE TITLE
Remove spelling mistake from README.md

### ISSUE THREAD

**Issue by mihai-burduselu** [systers/FirstAide-web#53]
![spelling-mistake](https://cloud.githubusercontent.com/assets/16403502/21771327/96be39e6-d68f-11e6-8c56-f4fe61990809.jpg)

**Comment by Afrin14** [comment]
If no one is assigned to this issue yet, then can I take it?

**Comment by mihai-burduselu** [comment]
Hello, I've made a pull request for this issue.

**Comment by Afrin14** [comment]
Since no one is assigned yet(Assignees : Not one assigned), so I fixed this issue and have made a pull request  too.

**Comment by mihai-burduselu** [comment]
![issue](https://cloud.githubusercontent.com/assets/16403502/21928066/6acac4e4-d991-11e6-8cb7-ae057c1181e1.jpg)

**Comment by Afrin14** [comment]
I was just too excited to solve this issue as this is my first ever contribution to open source.I am glade that I got to do it in this organizations.  And thanks to you too @mihai-burduselu  :smile:

**Comment by mihai-burduselu** [comment]
Ok, I am also new in open source world and I wanted to report and solve some issues.
This organization has great projects and I have some ideas for new features.
We can collaborate and we can talk more about new features and solving bugs on slack. :+1: 
I've left you a message.

There are also a lot of newcomers bugs in open source projects. Below it's a list of organizations with some guides for newcomers:
https://wiki.debian.org/qa.debian.org/GiftTag
https://wiki.gnome.org/Newcomers

**Comment by Afrin14** [comment]
That seems a great idea!
