### ISSUE TITLE
ReadMe section for Linux Users

### ISSUE THREAD

**Issue by anweshknayak** [systers/FirstAide-web#58]
Currently only for Windows. Should be updated for Linux users

**Comment by AkankshaBodhankar** [comment]
@anweshknayak Can you elaborate?

**Comment by anweshknayak** [comment]
I mean the setup installation has been provided only for Windows user. I use linux. It is bit different from the setup conventions that of windows. So I was asking to provide the setup instructions for the same @AkankshaBodhankar

**Comment by AkankshaBodhankar** [comment]
@anweshknayak Sure. You can solve this. Before making a PR post in the changes in the comments here.

**Comment by anweshknayak** [comment]
@AkankshaBodhankar sure

**Comment by Toppo96** [comment]
I am also a linux(ubuntu 14.04LTS) user and I want to add the readme section for linux(ubuntu 14.04LTS or its newer version) users. Can I work on this?

**Comment by AkankshaBodhankar** [comment]
@anweshknayak Are you working on this?

**Comment by anweshknayak** [comment]
@AkankshaBodhankar No. Feel free to assign to someone else

**Comment by Rupinderwadali** [comment]
I setup the application on both the operating system. I am willing to work on this. Should I?

**Comment by AkankshaBodhankar** [comment]
@Rupinderwadali You can work on updating the readme for linux users

**Comment by AkankshaBodhankar** [comment]
Will be covered under #166
