### ISSUE TITLE
Comments for Javascript files

### ISSUE THREAD

**Issue by AkankshaBodhankar** [systers/FirstAide-web#59]
**Pick only one file at a time.** 
This is a beginner task. You can claim one css file and start working on it
Make sure the format you use while adding comments is according to this 
http://usejsdoc.org/about-getting-started.html.

**Comment by AkankshaBodhankar** [comment]
The format should be according to http://usejsdoc.org/about-getting-started.html

**Comment by AkankshaBodhankar** [comment]
You can claim any file except:
sweetalert.min.js
jquery-1.12.4.min.js
dragscroll.js

**Comment by anweshknayak** [comment]
@AkankshaBodhankar can I work on this ?

**Comment by AkankshaBodhankar** [comment]
Which file do you want to work with ?

**Comment by anweshknayak** [comment]
https://github.com/asvd/dragscroll? to start with. can you elaborate a bit more like this library needs to be implemented right with the FirstAide web project ?

**Comment by AkankshaBodhankar** [comment]
I didn't get you

**Comment by anweshknayak** [comment]
You said : You can claim one css file and start working on it.
Like we need to integrate this library with the Project?

**Comment by AkankshaBodhankar** [comment]
No. You just need to add comments to one file and make a PR. There is no
need to integrate any library.

**Comment by fatimarafiqui** [comment]
Can I do this?

**Comment by AkankshaBodhankar** [comment]
Which file would you like to take? Before starting you must pick a file and
then start. Only one file must be picked.

**Comment by sudhachauhan** [comment]
is this still open? according to me all the js files are with comments.

**Comment by AkankshaBodhankar** [comment]
Yes it's still open. There are comments but, they have to be modified according to the commenting format.

**Comment by sunakshi96** [comment]
Hey @AkankshaBodhankar 
I am Sunakshi from Indian and I would like to claim /css files/menu-css.css  to contribute to the project

**Comment by AkankshaBodhankar** [comment]
This is the issue for javascript comments not css

**Comment by sudhachauhan** [comment]
Can I take popup.js ?

**Comment by AkankshaBodhankar** [comment]
@sudhachauhan Okay

**Comment by mani-rao** [comment]
Hey. Can I take PCMOpopup.js?

**Comment by sunakshi96** [comment]
Hey ,
Can I take circleOfTrustMessage.js  for this task ?

**Comment by Rupinderwadali** [comment]
@AkankshaBodhankar I am willing to work on this task. Is this issue still need contribution? Please let me know if I can contribute. 

Thanks

**Comment by AkankshaBodhankar** [comment]
@Rupinderwadali Which file would you like to take up

**Comment by MehaKaushik** [comment]
This is a beginner task, for anyone who is interested in contributing to the community, this is a good start.

**Comment by npari** [comment]
@MehaKaushik Is this a duplicate?

**Comment by ihsavru** [comment]
Hi, can i take up circleOfTrustMessage.js?

**Comment by MehaKaushik** [comment]
@npari No this is not a duplicate. The other issue is for css files. 
Hi, @ihsavru Thankyou for your interest. We would be more than happy to see you contribute, please go ahead and get in touch with any of @fatimarafiqui @npari and me, in case of doubts. 
Please push your work on  a separate branch and send a PR once done.
