### ISSUE TITLE
Documentation for database setup for new users

### ISSUE THREAD

**Issue by fatimarafiqui** [systers/FirstAide-web#60]
There is no documentation for initial database setup. For new users, it will not be easy to setup all the tables in database. We can add documentation for the same.

**Comment by anweshknayak** [comment]
Yes agree with that. Same for linux users too

**Comment by fatimarafiqui** [comment]
@anweshknayak It remains same for linux, mac or windows. The procedure is not OS dependant.

**Comment by AkankshaBodhankar** [comment]
@fatimarafiqui Sure. What do you propose to add in the documentation? Can you elaborate?

**Comment by fatimarafiqui** [comment]
There are no steps specified for database setup for the first time users. For example, If I download the zip and run the setup, it shows db not connected on the signup/ login page. Steps for db schema setup and connection are not specified.

**Comment by AkankshaBodhankar** [comment]
@fatimarafiqui 
You've got me wrong. I meant what will your documentation consist of for example.,
Steps to setup then,
what can go wrong then, 
few screenshots
etc.

**Comment by fatimarafiqui** [comment]
Yes, It would consist of screenshots and the procedure, step by step.
