### ISSUE TITLE
Add check for country field

### ISSUE THREAD

**Issue by fatimarafiqui** [systers/FirstAide-web#63]
There is no check for value accepted in the country field on the signup page. It is accepting any value, as shown in the screenshot.

<img width="1257" alt="screen shot 2017-02-07 at 23 45 51" src="https://cloud.githubusercontent.com/assets/13470643/22705040/edacaf3c-ed8f-11e6-8e0a-02bcba0ad5e2.png">

<img width="1273" alt="screen shot 2017-02-07 at 23 46 19" src="https://cloud.githubusercontent.com/assets/13470643/22705041/edb91358-ed8f-11e6-94d8-d2bab0874836.png">

I would suggest we can use a dropdown that enlists all the countries. @AkankshaBodhankar

**Comment by AkankshaBodhankar** [comment]
Sure. It's a good suggestion, I'll tell you which countries will go in the dropdown then, this issue can be reolved

**Comment by fatimarafiqui** [comment]
@AkankshaBodhankar sure. Please tell me the countries that need to be included. Or shall I include all?

**Comment by swapsha96** [comment]
@fatimarafiqui @AkankshaBodhankar Dropdown is a good option. Should I give it a head start?

**Comment by fatimarafiqui** [comment]
@swapsha96 I have already done it.
