### ISSUE TITLE
Confirm password field missing on signup page

### ISSUE THREAD

**Issue by fatimarafiqui** [systers/FirstAide-web#64]
An extra field for confirm password must be there because human typing errors are inevitable. The double entry of password ensures that the user has entered the right and desired password. It also prevents him from making more mistakes and signing up again. @AkankshaBodhankar 

<img width="1017" alt="screen shot 2017-02-08 at 00 03 07" src="https://cloud.githubusercontent.com/assets/13470643/22705650/6ad7da02-ed92-11e6-85b9-9965189f0ea2.png">

**Comment by AkankshaBodhankar** [comment]
Okay, Go ahead with this make sure you stick to the format while coding
