### ISSUE TITLE
missing link for sign in registration.php

### ISSUE THREAD

**Issue by sudhachauhan** [systers/FirstAide-web#69]
![screenshot 112](https://cloud.githubusercontent.com/assets/17814636/23401500/f78b339a-fdcd-11e6-96e9-39b500cc4354.png)
A link for sign in should be provided on the registration page too.
Otherwise a user has to use back button of the browser to get the sign in page.(in case of no account creation)

**Comment by AkankshaBodhankar** [comment]
The page will be redirected to login when the registration is completed.

**Comment by AkankshaBodhankar** [comment]
Why do you think it will be necessary to put a link? If the form is incomplete it won't be a good option to put a link.

**Comment by sudhachauhan** [comment]
Actually, Google signup and similar groups provide this link at every page, till the user registers. So, I thought there's no harm learning from such examples . So, why we should force the user to fill up the form, he might change his mind . just a suggestion.

**Comment by AkankshaBodhankar** [comment]
@sudhachauhan Solve this and then go for other issues. This is a valid issue. Add the link below the submit button.

**Comment by sudhachauhan** [comment]
![screenshot 121](https://cloud.githubusercontent.com/assets/17814636/23655674/fda631ba-035b-11e7-9e31-ec851ef9ec9f.png)
is this fine?

**Comment by AkankshaBodhankar** [comment]
The already have an account and sign in should be in one line
