### ISSUE TITLE
Requirement for feature 'User Persona'

### ISSUE THREAD

**Issue by AkankshaBodhankar** [systers/FirstAide-web#7]
User persona is a new feature and there is no mention of it in the PCSA mobile apps. There is just one mockup in the initial prototype posted by @MeepyMay. However, the ambiguity still exists as the mobile ans web apps must be in sync and there is no such requirement in mobile apps. 
@MeepyMay Do we need to implement this feature? And if yes, then what are the specific requirements ? Do they want another tab called profile or it'll just be in setting? Is there a detailed design already created which may be used? And also, is the profile visible only to the user or it is like facebook where everyone can see each other's profile?
_Urgent response required if to be covered in GSOC16_

**Comment by AkankshaBodhankar** [comment]
Description:
User persona displays the details of the users.

Mocks:
https://github.com/systers/FirstAide-web/issues/1 (The user persona prototype here)

Content:
NA

Acceptance criteria:
Add the feature and make a PR with appropriate screenshots.

**Comment by ReginaTL** [comment]
So looking at Issue #1 and the mock-up provided there I believe I can add some clarification to this issue. When designing an app from a user experience perspective an often used tool is the User Persona. A persona is an imaginary person that the designer creates to represent a type of user that may be using the app. Personas often show the technical abilities and other technical restrictions that users may have that need to be addressed in the design. 

Looking at the user personas provided to us we can glean some information about some potential issues with the design of the app. For instance, both Rowan and Peyton have slow internet access while Sean has no internet access at all. This lets us know that our users will likely have slow to no internet. To address this the app should be lightweight and potentially have the ability to work partially off-line. Some of the other information in there we can assume was incorporated into the mock-ups that were given to us. 

The important thing is that User Personas are not a feature to be implemented but a tool to let us know what kinds of users we need to design our app for. If you're confused about what I'm saying you can look at [Wikipedia's simple explanation](https://en.wikipedia.org/wiki/Persona_(user_experience)), [usability.gov's explanation](https://www.usability.gov/how-to-and-tools/methods/personas.html) or [Smashing Magazine's](https://www.smashingmagazine.com/2014/08/a-closer-look-at-personas-part-1/) more detailed explanation. I hope this helped some.

**Comment by AkankshaBodhankar** [comment]
@ReginaTL That's a great inference. It was really nice that you thought out of the box. We will take in your suggestion and discuss about it. I'll update the story soon with more details.
