### ISSUE TITLE
Forget Password Link and allowing Users to login with username too

### ISSUE THREAD

**Issue by VictorAlagwu** [systers/FirstAide-web#70]
Telling a user to log in using only his/her email is really stressful,most users will prefer being able to log in using both username and email, and lastly I think there should be a forget password link that allows users who forgot their password to be able to recover them

**Comment by swapsha96** [comment]
@VictorAlagwu this issue can be addressed by using 'Cookies'. Should I start working on this?

**Comment by AkankshaBodhankar** [comment]
@VictorAlagwu Sure. You can work on this issue.

**Comment by VictorAlagwu** [comment]
First, I would be working on the login aspect..then the forget password

**Comment by AkankshaBodhankar** [comment]
You can work on the forgot password issue, As of now let's keep the username as suggestion I'll let you know if it gets accepted.

**Comment by VictorAlagwu** [comment]
ok

**Comment by VictorAlagwu** [comment]
will be working on this towards the end of thiss week, i have exams to write

**Comment by AkankshaBodhankar** [comment]
@VictorAlagwu Are you working on this?

**Comment by VictorAlagwu** [comment]
was working on it until my laptop got stolen, so for now No i am not
working on it

On 5/17/17, AkankshaBodhankar <notifications@github.com> wrote:
> @VictorAlagwu Are you working on this?
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/systers/FirstAide-web/issues/70#issuecomment-301976587


-- 
Victor Alagwu
+234(817)-044-9567
www.victoralagwu.me
www.github.com/VictorAlagwu
www.linkedin.com/in/victor-alagwu-08416b94/

**Comment by npari** [comment]
Sorry to hear that @VictorAlagwu. Would you like to work on this at a later time?

**Comment by VictorAlagwu** [comment]
I am not sure of the time I would get a new laptop,so someone else can do it

On 5/17/17, Nithya Pari <notifications@github.com> wrote:
> Sorry to hear that @VictorAlagwu. Would you like to work on this at a later
> time?
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/systers/FirstAide-web/issues/70#issuecomment-301984409


-- 
Victor Alagwu
+234(817)-044-9567
www.victoralagwu.me
www.github.com/VictorAlagwu
www.linkedin.com/in/victor-alagwu-08416b94/

**Comment by AkankshaBodhankar** [comment]
Okay no problem.

**Comment by npari** [comment]
@MehaKaushik Is this issue still required?

**Comment by fatimarafiqui** [comment]
This issue is no longer valid.
