### ISSUE TITLE
Email Verification

### ISSUE THREAD

**Issue by fatimarafiqui** [systers/FirstAide-web#71]
There is no method for email verification. Anyone will any fake or non-existant email id can create can account. Proper verification check needs to be applied.

**Comment by Dhara159** [comment]
@fatimarafiqui I am Dhara Vihol and I would like to work in this project as a GSOC 2017  participate. but i have certain doubts:

1. Can anyone try to solve this issue or issue will be assigned to particular person. If it is so then I would like to submit solution code for this issue.
2. If this issue is assigned to me, where i have to do changes: In the original file on GitHub or providing the code over here?

**Comment by swapsha96** [comment]
@fatimarafiqui Verification can be done by adding another column 'isVerified' under 'user' table and sending verification mail to him/her. Should I start working on this?

**Comment by fatimarafiqui** [comment]
@Dhara159 @swapsha96 A person who created the issue, automatically the issue is assigned to that person on approval of issue, unless the issue is declared free. I will be creating a PR in a short while. Kindly refer Read section of documentation for more contribution details.

**Comment by swapsha96** [comment]
@fatimarafiqu I want to participate in GSoC '17 and take this project. Can you suggest me what can I do and how can I give a head start?

**Comment by Dhara159** [comment]
@fatimarafiqui okay. Thank you for your instruction. 👍

**Comment by AkankshaBodhankar** [comment]
@fatimarafiqui This issue is under hole right now. We are going to work on it after the code is deployed. Email verification will not be done on local machine.

**Comment by fatimarafiqui** [comment]
@AkankshaBodhankar Sure, Let me know if any progress comes up. I will take it up further.

**Comment by aparnavmenon** [comment]
Email ids in the database need to be validated. This has to be implemented by sending a computer generated email to every email id in the database. The user validates his email id by clicking on the computer generated link that has been mailed to the user.

**Comment by AkankshaBodhankar** [comment]
Will be done during the deployment of the app.
