### ISSUE TITLE
Spelling mistake in menu.php

### ISSUE THREAD

**Issue by Raxerz** [systers/FirstAide-web#72]
The word "harassment" is incorrectly spelled under "Sexual Assault Awareness"

**Comment by Raxerz** [comment]
Can I submit a PR for this?

**Comment by AkankshaBodhankar** [comment]
@Raxerz Can you post the screenshot?

**Comment by Raxerz** [comment]
![148864615571740](https://cloud.githubusercontent.com/assets/16686007/23580485/bf0ba41a-0128-11e7-8648-8f68c667c586.png)
Here you go @AkankshaBodhankar
The mistake is highlighted in black
