### ISSUE TITLE
Validation of Contact no. according to selected country

### ISSUE THREAD

**Issue by Dhara159** [systers/FirstAide-web#75]
Any length of contact no. is accepted without checking if it is correct according to the selected country or not on the page of editComrades.php.( Circle of trust / My Trustees)

![screenshot 156](https://cloud.githubusercontent.com/assets/12209363/23569650/51a11fec-0086-11e7-95c0-2e64c223176b.png)
![screenshot 158](https://cloud.githubusercontent.com/assets/12209363/23569670/701ce348-0086-11e7-8af4-8eb676956a07.png)

So, we can have many solution like dropdown for selecting the country first and after that validating it. but we have another solution like user has already selected the host_country at the time of registration. So, we don't have to ask again and again to user about country and we can directly select the country code by fetching the data from the database.

**Comment by AkankshaBodhankar** [comment]
This is a duplicate issue. There is a discussion going on already. Please go through the previous issues before creating a new one. #23
