### ISSUE TITLE
Unwanted styling on window resize

### ISSUE THREAD

**Issue by swapsha96** [systers/FirstAide-web#76]
![firstaide - google chrome](https://cloud.githubusercontent.com/assets/14021461/23567367/fc38947c-007b-11e7-9b0c-e5dda1d3f8c2.png)

As it can be observed that we get unwanted results on resizing window. Therefore, the website is not responsive. Best way to resolve this is to use BootStrap to make website mobile friendly. I can strap working on it by applying on few pages.

**Comment by AkankshaBodhankar** [comment]
Please go through the previous issues before creating one. #42
