### ISSUE TITLE
No password encryption

### ISSUE THREAD

**Issue by swapsha96** [systers/FirstAide-web#77]
![localhost 127 0 0 1 pcsa_web user phpmyadmin 4 5 1 - google chrome_2](https://cloud.githubusercontent.com/assets/14021461/23567554/d19136ce-007c-11e7-8f1a-0651bcc58285.png)

This is a major issue needs to be address. For the start **md5 encryption** can be used. This will be done at the time of both login and registration.

**Comment by sudhachauhan** [comment]
@swapsha96 We can use better hashing algorithms such as crypt().  Since the crypt() hashed passwords are self-contained, with all the information on the algorithm and salt required for future password verification, I think we should go with crypt().

**Comment by swapsha96** [comment]
Ok I'll use crypt() then create a pull request.

**Comment by swapsha96** [comment]
@sudhachauhan If we see the use of crypt(), it requires fetching the value of 'password' cell corresponding to email ID entered at the time of login. But `login('$password','$email')` is used already. Both cannot be used at the same time as that would be pointless. I think for now, MD5 encryption is sufficient because no such 3rd party integration is done.

**Comment by AkankshaBodhankar** [comment]
This is a duplicate issue. Go through the previous issues before creating a new one. There is a discussion on this going on in #48

**Comment by swapsha96** [comment]
@AkankshaBodhankar I resolved this issue using MD5 encryption. Should I create PR? Thank you for your assistance.

**Comment by AkankshaBodhankar** [comment]
@swapsha96 See the comments I've posted on your pull request.
