### ISSUE TITLE
Can not successfully send message or voice call after implementing twilio

### ISSUE THREAD

**Issue by Dhara159** [systers/FirstAide-web#78]
After setting the SID, authtoken, fromnumber and tonumber, Can not send the message or do voice call on given Tonumber. Showing error like :**Form submission canceled because the form is not connected** in get help now section.

**Comment by AkankshaBodhankar** [comment]
Can you post the screenshot of the error ?

**Comment by Dhara159** [comment]
@AkankshaBodhankar Here is the screenshot in which there is an error in twilio-call.js when i try to call and error in twilio-sms.js when i try to send sms in Get Help Now.
![screenshot 160](https://cloud.githubusercontent.com/assets/12209363/23581096/fe39b9dc-0133-11e7-8ba6-638a23b37cf2.png)

**Comment by AkankshaBodhankar** [comment]
You can use the slack channel to check if others are facing same problem. I'll look into it as well.

**Comment by Dhara159** [comment]
@AkankshaBodhankar I will surely discuss above problem on the slack channel. But I have found the solution. If you allow can I post why I'm facing this error.

**Comment by AkankshaBodhankar** [comment]
Sure.

**Comment by Dhara159** [comment]
We were not facing the issue in the older version of all the browser. But in updated version of browsers(I.e. chrome 56, Mozilla and IE 11)there will be such error. Because in the updated version it is strictly recommended to associate form in browsing context. If it's not, form submission will be blocked. So the we have to add **document.body.appendChild(form);** line in our both of the js file. It's like writing <form> in <body> in HTML. But before doing anything I'll surely confirm about this error on slack channel.

**Comment by AkankshaBodhankar** [comment]
This is a valid issue. Can you post the screenshot of the working version after you successfully made modifications

**Comment by Dhara159** [comment]
Sure. Here is the Screenshots:
1.) Selecting Voice call option from Get Help Now page:
![screenshot 161](https://cloud.githubusercontent.com/assets/12209363/23585540/7f861bac-01a7-11e7-92f8-e745e5faa33e.png)

2.)Option for making a call which was showing before fixing the issue.
![screenshot 162](https://cloud.githubusercontent.com/assets/12209363/23585548/a1307d56-01a7-11e7-93ad-35580b4e46d7.png)

3.) Popup for call successfully started.
![screenshot 163](https://cloud.githubusercontent.com/assets/12209363/23585553/bff31078-01a7-11e7-98e5-0e1576c331d8.png)

And there is no error or warning which was showing before applying fix.

**Comment by AkankshaBodhankar** [comment]
Okay. Fix this

**Comment by Dhara159** [comment]
I have fixed this by adding document.body.appendChild(form); before form.appendChild(input); in twilio-call.js and twilio-sms.js on line no. 15. because form.appendChild(input) was using form element.

**Comment by AkankshaBodhankar** [comment]
Alright. Will you change them and send a PR or you want me to do it?

**Comment by Dhara159** [comment]
Okay. I'll do it. Thank you for your help :)
