### ISSUE TITLE
Comments for PHP files. 

### ISSUE THREAD

**Issue by shreyans29** [systers/FirstAide-web#79]
While going through the codes, I did not find comments on PHP files and there is no other issue opened to take care of this. Is it okay if I go ahead with it @AkankshaBodhankar ?

**Comment by AkankshaBodhankar** [comment]
@shreyans29 Sure. Is there any particular format you will stick to?

**Comment by shreyans29** [comment]
Yes, this one https://phpdoc.org/docs/latest/getting-started/your-first-set-of-documentation.html

**Comment by AkankshaBodhankar** [comment]
Okay. But, for starters you can claim two files and start working on them.

**Comment by Rupinderwadali** [comment]
@AkankshaBodhankar Is this issue still up. Can I work on this issue?

**Comment by AkankshaBodhankar** [comment]
@Rupinderwadali You can pick one file.

**Comment by safrin96** [comment]
Hi, Can i pick circleOfTrust.php?
