### ISSUE TITLE
Adding Username with Logged in as

### ISSUE THREAD

**Issue by shreyans29** [systers/FirstAide-web#80]
[https://github.com/systers/FirstAide-web/blob/develop/project-docs/prj%20images/Screenshot%20(606).png](url)

In the project, I found that Logged in as was there without a username. Is it okay if I proceed to solve this. @AkankshaBodhankar

**Comment by AkankshaBodhankar** [comment]
@shreyans29 The link is leading to a 404 error. Can you post the screenshot.

**Comment by shreyans29** [comment]
![screenshot 606](https://cloud.githubusercontent.com/assets/8592568/23578615/558380ac-0101-11e7-9e93-9ae092e0ed42.png)

This image, the left bottom part.

**Comment by AkankshaBodhankar** [comment]
@shreyans29 Sure go ahead with this
