### ISSUE TITLE
Requirements for welcome page buttons

### ISSUE THREAD

**Issue by shreyans29** [systers/FirstAide-web#84]
The buttons on the welcome page are not functional. What can we do about it ?

**Comment by AkankshaBodhankar** [comment]
I'll forward this to the peace corps. You can work on it once we get the requirements from them. Until then we will keep it on hold.

**Comment by shreyans29** [comment]
how about we add something like coming soon message when clicked.

**Comment by AkankshaBodhankar** [comment]
Description:
The welcome page buttons are not functional. The requirement will be updated soon.

Mocks:
https://github.com/systers/FirstAide-web/blob/develop/project-docs/prj%20images/Screenshot%20(605).png

Content:
NA

Acceptance criteria:
Add the feature and make a PR with appropriate screenshots.

**Comment by AkankshaBodhankar** [comment]
Will be done under recommendation systems.

**Comment by MehaKaushik** [comment]
@fatimarafiqui what is the status for this issue? From what I remember, it is covered, please correct me if I am wrong.

**Comment by fatimarafiqui** [comment]
@MehaKaushik Yes, this is no longer relevant
