### ISSUE TITLE
Refactor Registraction Page and adding a User ID to user table

### ISSUE THREAD

**Issue by VictorAlagwu** [systers/FirstAide-web#87]
Going through the registration page and I saw some things that need to be corrected, first is the use of CALL in our mysql command,I think the normal SELECT statement should be used,and we should use the filter_var function to validate that correct emails are inserted, and also we will need to add some more columns to the database,id column, column for resetPasswordToken,and also resetPasswordCompleted

**Comment by AkankshaBodhankar** [comment]
Using stored procedures is always good from security point of view especially when you are passing parameters. That's the reason why we have chosen to use them. Why do you need an additional user ID when you can identify the user using the email id. It will be redundant. Email verification issue has been opened and is on hold. There is an ongoing discussion #71. 
When you are creating an issue please give a solid reason why you are thinking that this is a better way. If you want to add id then why is it required ? If you want to use plain select queries then why do you think it will be better choice. If you are planning to add the reset token then isn't it redundant ? You can work with the current password column to do it.

**Comment by AkankshaBodhankar** [comment]
Please give a reason why you want to make such changes. If your reason is solid and will improve the app we will always accept it. If you still feel that whatever changes you are suggesting are good then you can describe how will it improve the app and make it perform better.

**Comment by VictorAlagwu** [comment]
Ok
