### ISSUE TITLE
Change background color of "Set your peer counselling preferences" on the welcome page

### ISSUE THREAD

**Issue by Raxerz** [systers/FirstAide-web#89]
Currently this particular option or button ("Set your peer counselling preferences") has a different background color in comparison to the rest of the options. 
Is this how it's supposed to be or is it a bug that has to be fixed?
![screenshot from 2017-03-04 22 01 35](https://cloud.githubusercontent.com/assets/16686007/23580732/fb931afe-012c-11e7-96ee-9d646d4b285c.png)

**Comment by AkankshaBodhankar** [comment]
It's intented to be this way.
