### ISSUE TITLE
Recreating the Login and Registration Page-adding more advanced technologies 

### ISSUE THREAD

**Issue by VictorAlagwu** [systers/FirstAide-web#90]
I think technology is advancing everyday,and as a result of that I think a lot of stuffs need to be remove and added to the login page
*Hashing Passwords
*Creating a direct table for users
*Stop the use of  CALL functions 
*Create a new database with new columns in user table
*Forget Password feature
*Remember me feature
*Email verification
*Adopt the use of a PHP framework eg codeigniter
etc

**Comment by AkankshaBodhankar** [comment]
Many of the issues you are mentioning are redundant. 
Discussion on hashing passwords us going on #48
Email verification discussion is also going on in #71
What do you mean by direct users table? 
What new columns do you want to add in the user table?
Remember me feature has been suggested and it's valid as well. If you get any ideas to improve the app create different issues to address a particular problem and elaborate how it will improve the app and how you are going to solve it.
I've mentioned in your previous issue why we use stored procedures. Why do you think we should stop using them ?

**Comment by AkankshaBodhankar** [comment]
I think you have mentioned about forget password in another issue which was accepted. Why here again ? Please create issues surrounding to a particular and direct problem. If you are suggesting so many things use the mailing list. Use issues only to solve technical problems and related stuff. If you are suggesting changes and improvements which will require a lot of change and decision making use the mailing list.
