### ISSUE TITLE
Stay Signed In option on Sign In page.

### ISSUE THREAD

**Issue by Dhara159** [systers/FirstAide-web#91]
@AkankshaBodhankar Can we give such option like Stay Signed In to user whether wants to keep logged in untill he/she logout or allow him to logout after some time automatically? If it is then Can i start my work for this?

**Comment by AkankshaBodhankar** [comment]
Okay.

**Comment by Dhara159** [comment]
I have added keep me logged in functionality. In which user logs out automatically if user didn't select **Keep me logged in** Option. But if user has selected option, user will be actively logged in for some time. Here i set the time for 1 hour. So, can i make PR for this @AkankshaBodhankar

**Comment by AkankshaBodhankar** [comment]
@Dhara159 Are you working on this?

**Comment by Dhara159** [comment]
yup. I have completed this task and made a PR. but by mistake PR has been closed by me. I have added the preview. Can you please tell me is that okay or should I do some changes @AkankshaBodhankar

**Comment by Dhara159** [comment]
Here is the link of PR :https://github.com/systers/FirstAide-web/pull/162

**Comment by Dhara159** [comment]
@AkankshaBodhankar I have added the new PR for this issue. #227 is the id of new PR
