### ISSUE TITLE
Disable same username registering

### ISSUE THREAD

**Issue by VictorAlagwu** [systers/FirstAide-web#94]
Like the feature when same email address cannot register, i think the same username should not be able to register twice, as it will affect the login page, when different users with the same usernames, but different emails try logging in
![img](https://cloud.githubusercontent.com/assets/15857679/23582461/c4940c7c-012a-11e7-84e7-a862751070bf.JPG)

**Comment by shreyans29** [comment]
The login page only accepts email which is a primary key, I will not effect the login.

**Comment by VictorAlagwu** [comment]
I think with the implementation of  issue #70 ,it would be a problem ,since issue #70 is about allowing users to log in with either Email or username

**Comment by AkankshaBodhankar** [comment]
As of now we do not need this because we already have a unique identification which is email. In #70 I've mentioned that we will keep this username issue on hold and if it gets accepted then you can work on it.
