### ISSUE TITLE
Updating user info like email, password, mobile numbers.

### ISSUE THREAD

**Issue by shreyans29** [systers/FirstAide-web#96]
While working with it, I found no way to change passwords and update email address. I would like to work on it, how do I proceed ?

**Comment by AkankshaBodhankar** [comment]
This will be addressed along with the 'user persona' feature of the app which is on hold #7

**Comment by aparnavmenon** [comment]
**Description:**
The application needs a user friendly UI that accepts information like email, password and mobile number. This information has to be stored to the database.

**Mocks**
Students are encouraged to get creative with the mock ups. Looking for aesthetic designs that show industry trend awareness and balance.

**Content**
"Email id"
"Password"
"Phone number"
"Submit"

**Acceptance criteria**

- The UI should be visually appealing and easy to use
- The information obtained through UI must be correctly reflected in database

**Comment by MehaKaushik** [comment]
@fatimarafiqui we have covered this right ? Please correct me if I am wrong.

**Comment by fatimarafiqui** [comment]
@MehaKaushik No this is a part of settings page.

**Comment by MehaKaushik** [comment]
Yes, this is covered in settings section. Thanks
