### ISSUE TITLE
This is a secure portal link in Registration page.

### ISSUE THREAD

**Issue by shreyans29** [systers/FirstAide-web#97]
In the registration page there is a link which says "This is a secure portal". I was not sure if this was supposed to be a link or just an info. 

If it is supposed to be a link are there any specific requirements for it ? 
If not then I think it would be better to remove it as a link and just post it as text.

**Comment by AkankshaBodhankar** [comment]
@shreyans29 Yes, we can change it to text.

**Comment by shreyans29** [comment]
should I do it ?

**Comment by AkankshaBodhankar** [comment]
Yes
