### ISSUE TITLE
Text on Menu Barely visible : Color change

### ISSUE THREAD

**Issue by shreyans29** [systers/FirstAide-web#98]
![capture](https://cloud.githubusercontent.com/assets/8592568/23584903/00fba1ce-0195-11e7-8c00-3c02b414b9b2.PNG)
The text on the left column of the menu is barely visible. I think changing color would help.

**Comment by AkankshaBodhankar** [comment]
@shreyans29 The colors have been specified according to this. https://github.com/systers/FirstAide-Android/issues/49
Can you verify if the same has been used for it or not?

**Comment by shreyans29** [comment]
yes, it is the same but again barely visible even there. 
![6d39fe4a-d4cc-11e5-8397-ca57505b0a7d](https://cloud.githubusercontent.com/assets/8592568/23584926/dca97534-0195-11e7-8e57-727d89c674cb.png)
